### ISSUE TITLE
add gnomad data to ui

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#1025]
- [ ] Include in filters / column selection
- [ ] Include in variant details page
- [ ] Determine how to relate gnomad and exac data

**Comment by amycoffin** [comment]
Here are the wireframes for implementation:
https://docs.google.com/presentation/d/1QY4zfMG0eI3a2IckTZviCeZxX0Knf0AOQbtZkj2h3rk/edit#slide=id.p

Regarding "relating gnomad and exac" in terms of the UI, it is okay to have two separate subtiles.
