### ISSUE TITLE
Update Question Mark Links to Help Page

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#1042]
Fix the Variant Details Question Mark --> Help Page Tile functionality. 

Currently, on production, the Functional Assay question mark does not auto-open the tile. Otherwise, they are working as expected. I also notice that on production, there are missing question marks on the Clinical Significance (LOVD) and Clinical Significance (ClinVar) tiles. There should be a grey question mark to the right of the v^ icon (as seen on the Allele Frequencies tile). Let me know if adding question marks should be a separate issue.

On beta, however, many of the question marks got mixed up in the reorganization. Most question marks take to the Help page, but do not open tiles. We should update the question marks to open the appropriate associated tile, such that they do not go further out of date.

**Comment by zfisch** [comment]
@falquaddoomi is this something you can tackle before Thursday or shall I take a crack at it?

My main concern prior to the production deployment is making sure we're not introducing any new problems, but of course if it's trivial to fix other issues along the way, let's do it!

**Comment by falquaddoomi** [comment]
@zfisch Sure, the issue isn't hard to fix. The root of the problem seems to be that many of the `id` fields that associated the help buttons with the headers in the help doc went missing when they were updated. I'm going through the help buttons and re-adding the id fields at the moment; I'll post a PR shortly (definitely before Thursday).

Regarding the missing question marks on the report tiles, I'll go ahead and those, too. I'll link them to the remaining unlinked subsections under "What data sources and fields are provided in Clinical Significance Tiles?"

**Comment by amycoffin** [comment]
@falquaddoomi can you point me to the file where ids are kept, so if my editing messes this up in the future I can re-add?

**Comment by falquaddoomi** [comment]
@amycoffin Sure, they're in the file `website/js/content.js` in the `helpContentResearch` variable.

For instance, this line makes the panel "What are the fields in the Variant Nomenclature Tile?" linkable via the symbol "variant-nomenclature": https://github.com/BRCAChallenge/brca-exchange/blob/master/website/js/content.js#L203. When the `id` field isn't specified the panels get a "slugified" version of their name as the linking ID, e.g., the title "Variant Nomenclature" would become the id "variant-nomenclature".

After a little investigation, it seems that it wasn't that the ids were missing, but that the title text changed that broke the association with the help buttons. Either way, using `id` going forward is going to be more reliable. (I believe all the panel header help buttons are now linked by id, so we'll only need to worry about this when we introduce new help section/UI elements.)
