### ISSUE TITLE
Strange packing of tiles in Summary view on beta

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#1060]
On beta, when you view a variant in Summary view, there is whitespace at the upper left of the screen where the first tile should be.  See the attached screen shot.  This isn't happening on production.

<img width="1111" alt="Screen Shot 2019-05-26 at 3 23 03 PM" src="https://user-images.githubusercontent.com/1714823/58387810-4d638580-7fca-11e9-9f86-35638ed515d8.png">

**Comment by zfisch** [comment]
Curious, @melissacline do you see this upon first loading the page or only after switching to summary view from detail view? Also, what browser window size are you seeing this on?

I currently only see it happen if I switch from detail to summary view, but not if I load summary view directly.
