### ISSUE TITLE
add donate button

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#1074]

**Comment by amycoffin** [comment]
Here are the wireframes for the donate button:
https://docs.google.com/presentation/d/1oPuG3hzzTNmC7kT3HGvVyZaOhDLV6ic3X8O3JRG7D70/edit?usp=sharing

@melissacline I consider it medium-to-high priority to update the "This Site" page to be more donor friendly. I can streamline that ASAP, using grant materials and the GA4GH videos. This is easier than tackling any of the content on the Facts & Stats page, but has the downfall of not taking users to the eye candy. We could also link to Facts & Stats, but the title of that page makes it confusing IMO.

**Comment by zfisch** [comment]
Looks good -- I understand the donation form and processing will be managed by somebody other than ourselves and we're just linking to it -- is this correct?

**Comment by amycoffin** [comment]
Just to update this, we will no longer need to update the "This Site" page, because we will be linking to an updated "What is the BRCA Exchange?" item instead. Here is the google doc:https://docs.google.com/document/d/15ZFE-ViYvi8PCZUDMRQ63hiQ471PxG0yZ1tOEjD3r6g/edit
