### ISSUE TITLE
ClinVar variant with an HGVS coordinate that's off

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#1086]
Reported by Michael Parsons:

I was looking at https://brcaexchange.org/variant/209107 and noticed this nomenclature doesn’t match the ClinVar entries that it is linked to. Essentially it is a reported deletion of full exon 3 in BRCA2 but the BE website has it offset by 3 bases (5’). Of note it did come up when I put in c.68_316del which is good but still confusing for users that won’t know c.68-3_313del is actually the same variant. Using the HGVS 3’ rule it should be changed to c.68_316del but I think it is highly likely that the reporting lab would have originally called it complete exon deletion rather than the 3bp offset version.

Here's the issue.  We list its HGVS cDNA as c.68-3_313del249, which means: (1) start at nucleotide position 68, which is a splice site; (2) move 3 bases into the intron; (3) delete everything from there to Position 313.  The HGVS of c.68_316del  indicates deleting everything from cDNA nucleotides 68 to 316.  So we indicate that we're deleting the correct amount, but not from exactly the correct bases.  Did we derive this hgvs string?

**Comment by izcram** [comment]
This should be fixed #1125 as we are switching to biocommons hgvs. The output of that code reports `NM_000059.3:c.68_316del` for above mentioned variant in accordance with ClinVar.

**Comment by melissacline** [comment]
This has in fact been fixed - yay!
