### ISSUE TITLE
Ctrl + F functionality doesn't work on Help pages

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#1090]
When we implemented tile functionality on the home page, it made it so that Ctrl +F no longer works. We should implement a way for people to search the help pages.

**Comment by amycoffin** [comment]
One starting point is perhaps auto-expanding anything with sub-tiles, so at least titles of subtiles are able to be found using ctrl + F

**Comment by falquaddoomi** [comment]
Closed by PR #1112.
