### ISSUE TITLE
Community Pages display phone numbers

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#1095]
I just wanted to bring it to our attention that some of the community members have phone numbers displayed, and I am not sure if this is intentional behavior.

**Comment by melissacline** [comment]
Nice catch!  I hadn't thought about this before, but agree that the phone number is intrusive.  @zfisch , this is not urgent, but whenever there's a good moment would you remove the phone number field?

**Comment by zfisch** [comment]
Indeed!

**Comment by zfisch** [comment]
@amycoffin @melissacline we actually allow users to hide their email and phone numbers if they want during sign up. do we still want to hide phone numbers even though we provide them this option?

**Comment by zfisch** [comment]
@amycoffin @melissacline following up on this

**Comment by zfisch** [comment]
@amycoffin @melissacline one more follow up before close -- to reiterate, users already have the option to hide email/phone number during sign up.

**Comment by melissacline** [comment]
Thanks!  Yes, let's close.
