### ISSUE TITLE
Donation Drive: Beta Updates

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#1096]
Hi Zack, 

Alexis had a few notes on Beta:

- home page: How Does the BRCA Exchange Benefit Patients? >> Capitalize "does"
- Video produced by the [Global Alliance for Genomics and Health](https://www.ga4gh.org/) and the [Broad Institute](https://www.broadinstitute.org/) >> link to their web pages.
- home page: ClinGen logo needs to link to https://clinicalgenome.org/
- http://beta.brcaexchange.org/about/thisSite >> Should this have the same logos as on the home page?

**Comment by zfisch** [comment]
Great! Will get these pushed up asap :)
