### ISSUE TITLE
Submission history pre-dates variant history for removed/added variants

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#1139]
When a variant has had a change in genomic coordinates leading to a remove+add, the variant details page for the “new” variant can show more submission history than variant history. 

For example, in Release 33, the old variant chr17:g.43093335:TTCTTTTTC>TCCTTTTT was replace with new variant chr17:g.43093336:TCTTTTTC>CCTTTTT.  Looking at this variant (http://brcaexchange-dev.gi.ucsc.edu/variant/272673) and scrolling down to the history, one sees variant history starting in October 2019, but ClinVar submission history starting in July 2018.  It looks strange to see submission history pre-dating variant history.  
 
This is low-impact, and is not worth any significant developer time to fix, but should be addressed somehow - as a documented known issue, if nothing else.

**Comment by zfisch** [comment]
@melissacline @amycoffin Did we decide how to handle this issue?

First order is to decide if it's better to hide submission history that predates variant history or if we prefer to show as much history as we can gather?

If we want to invest more time than leaving the current implementation, we could try to determine if variants with different Genomic_Coordinate_hg38 values are equivalent, but my estimation is that this will prove tricky, imperfect, and time consuming. Remember that we already check for equivalence in the pipeline, so we'd be essentially improving that same code and potentially trying to apply it retroactively. A good starting point would probably be to focus on different variants associated with equivalent submissions.

**Comment by zfisch** [comment]
Determined that this is in good shape for now.
