### ISSUE TITLE
exLOVD BRCA error variants: why are they erroneous?

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#1143]
In the release/artifacts directory, there are the files exLOVD_BRCA1_error_variants.txt and exLOVD_BRCA2_error_variants.txt.  At the top of the BRCA1 file are these lines:

Invalid HGVS cDNA allele "53T>C  ": could not parse hgvs field NM_007294:c.53T>C  
Invalid HGVS cDNA allele "380G>A  ": could not parse hgvs field NM_007294:c.380G>A  
Invalid HGVS cDNA allele "1001C>A  ": could not parse hgvs field NM_007294:c.1001C>A  

At the top of the BRCA2 file are these lines:

Invalid HGVS cDNA allele "3G>A  ": could not parse hgvs field NM_000059:c.3G>A  
Invalid HGVS cDNA allele "632-16A>C  ": could not parse hgvs field NM_000059:c.632-16A>C  
Invalid HGVS cDNA allele "1514T>C  ": could not parse hgvs field NM_000059:c.1514T>C  

I'm confused, because these look like normal HGVS expressions, and in fact are variants in our database.  Could you give me any more information on this?

**Comment by melissacline** [comment]
I actually see what's going on!  Looking more closely at the [exLOVD source repo](http://hci-exlovd.hci.utah.edu/variants.php?select_db=BRCA2&action=view_unique&order=Variant%2FDNA%2CASC&hide_col=&show_col=&limit=1000) I see that these variants have extraneous text in the HGVS columns, e.g. "632-16A>C (Reported 2 times)".  This looks like it impacts 16 BRCA1 and 40 BRCA2 variants.  

So that's the source of the problem.  I don't know how we should address it.  In the short term, let's add it to the known issues, and proceed with the release schedule.  It's too small a number for holding up the show.

**Comment by zfisch** [comment]
Ahhh interesting.. curious if there's other variants of these sorts getting skipped.

I think we split on semicolons to handle dual hgvs representations in some part of the pipeline, but we haven't tried to handle other delimiters or non-hgvs text AFAIK.

**Comment by zfisch** [comment]
fixed by commit 9a456daa24a240cb6ca46f2b43260782169c1096
