### ISSUE TITLE
Help Page Search Bar Malfunction

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#1145]
The search bar on the Help Page will search a term before you finish typing it. i.e. if i'm looking up "allele frequency" it might stop at "all" or "allele" and search that statically, without changing behaviors as the search term updates

**Comment by zfisch** [comment]
what browser etc? can you provide steps to recreate?

when i type in "allele frequency" in few letter increments it looks like it's working as expected (updates search results as i add new letters)

**Comment by amycoffin** [comment]
@zfisch the problem seems to have resolved... it might have been due to a slow internet connection? Not sure.
