### ISSUE TITLE
Update logos on Home Page

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#1153]

**Comment by amycoffin** [comment]
Here are the home page updates:
https://docs.google.com/presentation/d/1AFmeRTK7ZHPIpIhM0X6ITirIB8DgSQuSJoOUHG9JdSc/edit

**Comment by amycoffin** [comment]
@melissacline 

Can you review/comment on this list of logos that we need to add? There are some project names that I can't recall. It would also be helpful if you happen to have high-quality versions of any of these lying around. 

Collaborations
- [ ] gnomAD
- [ ] updated version of Human Variome Project (what is the name again?)
- [ ] specific work streams of GA4GH? 
- [ ] UW/Starita lab
Funders
- [ ] NIH BD2K
- [ ] NIH NCI ITCR 
- [ ] anything from gunnar's neck of the woods?

**Comment by zfisch** [comment]
@amycoffin following up on this issue -- where do we stand in terms of design and content? As soon as the designs are complete and all the content we need is available I'll make the changes :)

**Comment by melissacline** [comment]
Hi @amycoffin , thanks for having this list so well-organized!

The new logos to add are for Lea Starita (I'll email her right now to see what logo she would prefer), gnomAD (we can use the logo from their web portal).  The Human Variome Project seems to be trying to change their name to the Global Variome Project, but they don't appear to have a new logo, so what we've got is fine.

For funding agencies, we should acknowledge the support of the BD2K (sample logos attached)
![NIH-BD2K](https://user-images.githubusercontent.com/1714823/72112804-92d38980-32f3-11ea-97b5-69e116ca079e.png)
![DFvYfucXcAATaap](https://user-images.githubusercontent.com/1714823/72112805-92d38980-32f3-11ea-9889-ae9367af03c5.jpg)
![viewphoto](https://user-images.githubusercontent.com/1714823/72112806-936c2000-32f3-11ea-929a-a682d40db749.jpeg)

NCI ITCR (attached)
![ITCR_logo_700_x_400](https://user-images.githubusercontent.com/1714823/72112966-f3fb5d00-32f3-11ea-9d46-9befe20999c8.png)

And the NCI (attached)
![NCILogo2](https://user-images.githubusercontent.com/1714823/72112988-007fb580-32f4-11ea-913e-8b8b6743fc6f.png)
![NCILogo](https://user-images.githubusercontent.com/1714823/72112990-007fb580-32f4-11ea-9e54-393430243815.png)

Let me know how else I can help.

**Comment by melissacline** [comment]
Oh, about the GA4GH workstreams: not necessary.  Some but not all have their own logos.

**Comment by amycoffin** [comment]
@zfisch is it sufficient to list all the logos like this here as shown, or should we make a little google drive folder? Here is another one we will add, thanks to @melissacline's email to Lea. Regarding formatting, I will definitely update the wireframes so you don't have to think to hard about what goes where, but I am wondering what makes sense for the actual files. 
![BBI_Logo_Horizontal_RGB_4 color](https://user-images.githubusercontent.com/25374391/72171767-a4736a80-33a1-11ea-92db-76f7f345d33e.jpg)

**Comment by zfisch** [comment]
This is fine, as long as all the logos are attached to the issue (or linked to in the issue) and the wireframes have everything where you want it I'll be able to make it happen :)

**Comment by zfisch** [comment]
@amycoffin im actually a little confused -- the only updates i see in the wireframes are adding gnomad and the two nih logos https://docs.google.com/presentation/d/1AFmeRTK7ZHPIpIhM0X6ITirIB8DgSQuSJoOUHG9JdSc/edit#slide=id.g6be18153fd_0_164

am i missing something? what are the other logos in this thread?

**Comment by melissacline** [comment]
@amycoffin would you update the wireframes to show the new logos?  We could review them during our 1-on-1 today.

**Comment by amycoffin** [comment]
@zfisch @melissacline Sorry, I forgot to update them but the new logos are in there now. Happy to review them today.
