### ISSUE TITLE
Incorrect variant synonym

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#1167]
The variant in question is at BRCA Exchange at https://www.ncbi.nlm.nih.gov/clinvar/variation/55744/.  BRCA Exchange lists this variant as BRCA1  c.894_895del.  It pulls variation data from ClinVar for BRCA1 c.895_896del a.k.a. NM_007294.3:c.895_896delGT (see https://www.ncbi.nlm.nih.gov/clinvar/variation/55744/), and lists NM_007294.3:c.895_896delGT as a synonym.  Actually,  BRCA1 c.895_896del and BRCA1 c.894_895del are not equivalent: BRCA1 c.895_896del would delete a GT while  BRCA1 c.894_895del  would delete a TG.  Where did this merge come from?

**Comment by zfisch** [comment]
@melissacline this is the variant normalization issue we just resolved, correct?

aka #1187

**Comment by melissacline** [comment]
Yes, this is the same issue.  We can close this.
