### ISSUE TITLE
Resolve a UI ambiguity in the display of the protein priors

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#1189]
From Michael Parsons:

_I have a minor improvement suggestion for the priors tile. Looking at this variant page https://brcaexchange.org/variant/327245 I noticed that the protein prior has two different boxes with red highlight on the edges. While they both have the same probability, they are referring to different variant types. This one is a missense variant and therefore not a 'Silent'. It's a little thing but I think it will make it look more like we know what we're doing._

![image](https://user-images.githubusercontent.com/1714823/77975738-c220e380-72af-11ea-937c-2c441d8eafaa.png)

This arises because there are two different conditions that can yield the same numeric result for the protein prior, and the UI doesn't know which was the case.  A simple fix is to test the pyhgvs_protein field to see if this is a synonymous variant.  If pyhgvs_protein contains an equals sign, such as 'NP_000050.2:p.(Ala1193=)', then put the box around the Synonymous variant case, else put it around the missense variant outside key domains case.

**Comment by zfisch** [comment]
@melissacline this is a little tricky without more info... but here's what I've implemented:

If a variant is NOT synonymous (meaning there's no `=` in the hgvs_protein), don't outline the `Silent (synonymous)` field no matter what. Does this always hold true or shall we have a brief discussion to clarify?

**Comment by zfisch** [comment]
i should add... if a variant IS synonymous, is it safe to say the `Missense severity irrelevant` box should never be highlighted?
