### ISSUE TITLE
Popmax data missing for variant on the gnomAD display

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#1198]
For [this variant](http://brcaexchange-dev.gi.ucsc.edu:9003/variant/350891), the Popmax Filtering AF fields just below the graphs are blank.  In [gnomAD](https://gnomad.broadinstitute.org/variant/17-41202590-A-T?dataset=gnomad_r2_1_non_cancer), this variant has a Popmax Filtering AF of 0.1103, from the AFR population.

**Comment by zfisch** [comment]
working on it... looks like a UI issue since the correct AF is in the underlying data :)

**Comment by zfisch** [comment]
@melissacline fixed on dev, how many figures do we want to show or is it ok as is?

http://localhost:8080/variant/365132

**Comment by melissacline** [comment]
Awesome!  It looks like gnomAD does four digits after the decimal point (e.g.  0.1103), so let's go with that.
