### ISSUE TITLE
Add two more fields to the exLOVD / Multifactorial Analysis tile

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#1206]
This is a request from Michael Parsons.  The exLOVD data (a.k.a. the BRCA ex-UV data) has two additional fields that would be valuable for us to pull in: the Case-Control LR and the Pathology LR.  See [this entry](http://hci-exlovd.hci.utah.edu/variants.php?select_db=BRCA2&action=search_all&order=Variant%2FOpri%2CASC&hide_col=&show_col=&limit=100&search_pathogenic_=&search_Variant%2FExon=&search_Variant%2FDNA=c.9286G%3EA&search_Variant%2FDNA_bic=&search_Variant%2FProtein=&search_Variant%2FPosteriorP=&search_Variant%2FIARC_class=&search_Variant%2FPri_ref=&search_Variant%2FSec_ref=&search_Variant%2FAGVGD_priorP=&search_Variant%2FSplicing_priorP=&search_Variant%2FOpri=&search_Variant%2FCombined_priorP=&search_Variant%2FSegregation_LR=&search_Variant%2FPatho_LR=&search_Variant%2FSumFamHis_LR=&search_Variant%2FCooccurence_LR=&search_Variant%2FCaseCon_LR=&search_Variant%2FProduct_LR=&search_Variant%2FExtrinfo=&search_Patient%2FPhenotype%2FDisease=&search_Patient%2FReference=&search_Patient%2FDetection%2FTemplate=&search_Patient%2FDetection%2FTechnique=&search_Patient%2FRemarks=&search_Patient%2FTimes_Reported=), which corresponds to [this variant](https://brcaexchange.org/variant/344203) on BRCA Exchange.  

The Pathology LR and Case-Control LR have probably been part of the exLOVD data forever, but we didn't realize that there was good information that we weren't pulling in yet.  Hopefully, this is **"just"** a minor change to that web-scraping script (yeah, I know...).

**Comment by zfisch** [comment]
@melissacline could you provide a wireframe or if it's as simple as adding a couple rows, a description of where you would like the data displayed in the UI?

**Comment by melissacline** [comment]
You bet.  One wireframe coming up!

**Comment by melissacline** [comment]
[Here](https://docs.google.com/presentation/d/1Zyqh2sR6VB7UwDodRHIYE5aHJOO2hZECXsTTDX_sC50/edit?usp=sharing) is a quick wireframe.  @zfisch Let me know if you need anything else.

**Comment by zfisch** [comment]
@melissacline need a couple things to wrap this up:

1. Help text, e.g. https://brcaexchange.org/help#co_occurrence_lr_exlovd
2. Data dictionary text, e.g. ```Segregation_LR_exLOVD	Log ratio describing the likelihood of variant pathogenicity, given co-segregation data```	0.00001 (I could probably guess what would go here but better to confirm)

**Comment by melissacline** [comment]
@zfisch, here are some wrap-up things for you.
1. Help text:

- co-occurrence: the definition you have in place looks fine.
- Segregation Likelihood Ratio: This value reflects the likelihood of pathogenicity given the extent to which the variant segregates with disease in the pedigrees or family trees of individuals who carry the variant.  From ExUV.
- Summary Family History Likelihood Ratio: This value describes whether or not individuals who carry this variant come from families with significant histories of cancer.  From ExUV.

2. Data dictionary text: if you give me the field names, I'll take care of that.

Thanks!

**Comment by zfisch** [comment]
@melissacline I actually need the text for Pathology LR and Case-Control LR -- we already have co-occurrence, segregation, and summary family history text (unless you want those updated!)

The new fields in the output are called:

Segregation_LR_exLOVD
Pathology_LR_exLOVD

Reminder that we translate exLOVD to ExUV in the ui.

Changes can be made on the addExUVLRFields branch or can be done in their own PR afterwards if you'd like.

**Comment by melissacline** [comment]
Okay, I see.  The existing help text is fine.  Here's help text for the new fields::
Pathology_LR: This value is the likelihood ratio estimated from tumor pathology data from cancer patients who carry the variant.  From ExUV
Case-Control LR: This value is the likelihood ratio estimated from analysis of matched case (diagnosed with cancer) and control (unaffected by cancer) patients.  From ExUV.

To doublecheck, the new fields are called Pathology_LR_exLOVD and what?

**Comment by zfisch** [comment]
eep! good catch, thanks!

Case_control_LR_exLOVD
Pathology_LR_exLOVD

**Comment by melissacline** [comment]
Great - I've got a pull request up for you!
