### ISSUE TITLE
Add footnotes or help text hyperlinks to the classification text on the Expert Reviewed portal.

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#163]
Add the following text to the help text:
Expert Reviewed: denotes a reported variant which has not yet been reviewed by the ENIGMA group on behalf of BRCA Exchange
If it's easy, then add hyperlinks to the help text for all classification types (Benign, Likely Benign, Pathogenic, Likely Pathogenic, and Not Yet Reviewed).  Otherwise, add this text as a footnote below the Variants table.  See also #162.

**Comment by melissacline** [comment]
Amy, here's some old feedback.  Would you mark it down for the next round of changes to the Help text?

**Comment by amycoffin** [comment]
Will do! I will check with you once its done to make sure I understood correctly.
