### ISSUE TITLE
explore test_loadingscript.py on new data

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#204]

**Comment by zfisch** [comment]
@melissacline I've spent some time refactoring this script, but I'm confused as to the intent and am unsure where to take it at this point.

Is the intent to create a test that runs the pipeline over a static set of input data and ensures the output meets a certain set of criteria (i.e. all of the tests in test_loadingscript)? If so, creating static test data is necessary and keeping this as a unit test (will require further development) makes sense.

Is the intent to run these tests across final outputs (e.g. built_with_change_types.tsv) from each run of the pipeline to make sure the output meets the testing criteria? If so, then refactoring this as a final step in the pipeline to develop a report of outcomes would help us examine the final output data.

FWIW, I think both directions would be worthwhile and increase our confidence in the pipeline and the output data, but I need some clarification about what outcome you would like to see from my working on test_loadingscript.py.

**Comment by melissacline** [comment]
@zfisch Let's talk about this on Monday.  I think it would be really worthwhile to test that new incoming data matches certain assumptions, but I'm not sure that this is the right place to do it.

**Comment by zfisch** [comment]
Makes sense -- let me know when you'd like to discuss :)
