### ISSUE TITLE
automate process of adding releases.

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#224]
Currently, adding a new release requires some manual work of creating directories and moving files around. The steps are outlined in the brca-exchange/website/readme.md file.

It would be great to automate this process and possibly generate migrations to make sure these releases are re-added in the case that a new developer joins or the db needs to be rebuilt (currently, the first release is the only data added to the DB when running migrations).

**Comment by melissacline** [comment]
@zfisch is this still the case?  If so, how'd you like to address this for Feb 2018?
