### ISSUE TITLE
Add required packages to website README, and databaseUrl problem

### ISSUE THREAD

**Issue by uvesten** [BRCAChallenge/brca-exchange#227]
Tried installing the website on a recent Debian(jessie), but ran into some problems with missing packages, I assume it will be the same on a recent Ubuntu. Uploaded a patch here to fix. 

The relevant change is 

 * **Install the python dependencies**
    * `sudo apt-get install python-dev gcc libpq-dev libffi-dev libxslt1-dev libxml2-dev`
    * `pip install -qU -r requirements.txt`

Also, the `databaseUrl` in `js/backend.js` does not exist (anymore?), so I ended up editing `backend_url` in `page.template`.

[patch.txt](https://github.com/BD2KGenomics/brca-exchange/files/567844/patch.txt)

**Comment by melissacline** [comment]
@zfisch What should be done with this issue?
