### ISSUE TITLE
Bug in displaying literature changes

### ISSUE THREAD

**Issue by maryjgoldman** [BRCAChallenge/brca-exchange#324]
We don't want to show changes in literature if it is only the expansion of a reference (ie. Literature Reference (exLOVD): Tavtigian, S.V. et al., Journal of Medical Genetics 43: 295-305, 2006. Tavtigian et al. 2006). 

We do this by matching last name and ignoring if it's the same. The bug is that if the last name is followed by a comma, like in the case above, then it doesn't match the last name as it should.

http://brcaexchange-dev.cloudapp.net/variant/21245
c.2315T>C

**Comment by melissacline** [comment]
Zack, here's something for the next release

**Comment by melissacline** [comment]
This is an issue, but it's a small issue that really arises from the representation of data in one database.
