### ISSUE TITLE
build true/false test suite for pipeline

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#357]

**Comment by zfisch** [comment]
Test release data by checking it against a series of true/false tests -- could be run at the end of the luigi pipeline to produce a report about the data.

**Comment by melissacline** [comment]
@zfisch is this still open?

**Comment by melissacline** [comment]
@zfisch I feel like this issue has been addressed by your unit tests.  Can I close it, or does this represent something different to you?

**Comment by zfisch** [comment]
Yep, closing!
