### ISSUE TITLE
write test suite for pipeline output

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#359]

**Comment by zfisch** [comment]
6. Test release data by checking it against a series of true/false tests -- could be run at the end of the luigi pipeline to produce a report about the data.

**Comment by zfisch** [comment]
1. Run small set of data through the pipeline and run through several true/false (maybe generative as well) tests:
no bad merges
merges are successful
no lost data that we need
no artifact data that shouldn't be there
correct classifications
what are other major areas of concern?
2 variants get merged together within one source
2 variants get merged together from two different sources
A variant from each source gets merged together
A variant whose reference is incorrect does not end up in the final output
2 variants who have the same position but transition to a different base do not get merged together
A variant with only genomic coordinates gets correctly merged with a variant who only has cDNA coordinates

**Comment by melissacline** [comment]
@zfisch where are we on this?

**Comment by zfisch** [comment]
@melissacline just about where we started...

this came up on the call again today, adding @izcram in case either of us has some dedicated time to devote to it.
