### ISSUE TITLE
Erroneously pulling up the current version of a variant under Versioning?

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#364]
All Public Data portal, search for variant "chr17:g.38498662:C>G".
Shows a Nov 5 update of -Counsyl as a Submitter (ClinVar) (omitting a literature-only submission by Counsyl).
Clicked on the October 6 link.  On the Release Notes page, followed the link to New Variants.  Searched for the same variant.   Here, I would expect to see Counsyl as a submitter.  Here's what I actually see:

Breast_Cancer_Information_Core_(BIC)_(BRCA1),ITMI,Ambry_Genetics,GeneDx,Invitae,Evidence-based_Network_for_the_Interpretation_of_Germline_Mutant_Alleles_(ENIGMA)

Are we pulling up the current version of this variant rather than the October 6 version?

**Comment by zfisch** [comment]
Yep, the site is currently set up to only allow viewing the current version of a variant, or the most recent version of a variant if it was deleted. To see an older version of a variant as it currently stands, you would have to download the old data (I did confirm that Counsyl is included in the 10/6 release, as it should be).

**Comment by melissacline** [comment]
Thanks - that clarifies my understanding.

**Comment by zfisch** [comment]
Yep! I believe I asked the same question to Mary during Beta testing 😄
