### ISSUE TITLE
Get Google Analytics reporting again

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#376]
The link I currently have for BRCA Exchange Google Analytics is this:
https://analytics.google.com/analytics/web/?authuser=1#report/defaultid/a30159111w105300047p109579554/.  However, when I go to this link, Google Analytics redirects me to a sign-up page.  Would you figure out what's going on, is the BRCA Exchange Google Analytics offline (it seemed to be online about a week ago), or is the link wrong?  Thanks - this is urgent!

**Comment by maryjgoldman** [comment]
I have access to google analytics here: https://analytics.google.com/analytics/web/#report/defaultid/a30159111w105300047p109579554/ Let me know what you need and I can get you screenshots, numbers, whatever

**Comment by maryjgoldman** [comment]
Just realized that is the same link. Not sure why it's not working for you ...

**Comment by zfisch** [comment]
What's the email associated with the GA account? There are 0 existing accounts for brcaexchange@gmail.com.

**Comment by zfisch** [comment]
@maryjgoldman if you're able to access the data, please transfer ownership to brcaexchange@gmail.com. It can be done following these directions http://webapps.stackexchange.com/questions/893/transfer-ownership-of-google-analytics-accounts

**Comment by maryjgoldman** [comment]
Looks like I don't have permission? I wonder if @acthp is the owner and can add Melissa?
![untitled](https://cloud.githubusercontent.com/assets/13877333/22342913/dd0e0f8e-e3aa-11e6-933d-cce52d12bd2f.png)

**Comment by zfisch** [comment]
@maryjgoldman Sounds probable -- whoever set it up originally is probably the only one with admin permissions and they should be able to grant access and permissions to other gmail users.

I still think it's a good idea to at least give viewer access to brcaexchange@gmail.com so anybody with access to that account can see the data and report as necessary.

**Comment by acthp** [comment]
Give it a try, now. I added permissions for Melissa, Mary, and Ben.

b.c.

**Comment by melissacline** [comment]
It's working beautifully now!  Thanks, everyone, for the rapid response!!!
