### ISSUE TITLE
Add GA4GH Tests to CI

### ISSUE THREAD

**Issue by david4096** [BRCAChallenge/brca-exchange#389]
The django tests aren't a part of CI and should be.

From @zfisch in https://github.com/BD2KGenomics/brca-exchange/pull/387

>Looks good!
>
>BTW, we're now running django tests as part of the circleCI builds using pytest. If you'd like to include the tests for the GA4GH api, you could change `tests.py` to be something like `test_GA4GH.py`, and make a few updates to the import statements and setup (similar to those in `brca-exchange/website/users/test_views.py`, requirements need updating in `brca-exchange/test-requirements.txt`). The command that runs the tests is in the `brca-exchange/circle.yml` file: `cd .. && pip install -r test-requirements.txt && pytest --junitxml=${CIRCLE_TEST_REPORTS}/pytest-results.xml`

**Comment by melissacline** [comment]
@zfisch What do you think of this?
