### ISSUE TITLE
A Community Pages member from Kansas appears to be from Malaysia?

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#391]
Last month, we were trading emails with Soo-Hwang Teo <soohwang.teo@cancerresearch.my> from Cancer Research Malaysia, who was having trouble signing up on the community pages.  Today, I set about adding Soo-Hwang.  When I went to check if the map showed a new entry (for Selangor, Malaysia), I noticed this person whose map entry appeared to be in Malaysia, in or close to Selangor:
Alisdair Philp, Ph.D
Genetic Counselor
University of Kansas, Cancer Center
Maybe Alisdair Philp would prefer to be in Malaysia if the weather isn't so great in Kansas today, but I think he needs to go back to Kansas.  Is something out of sync, such that Alisdair got Soo-Hwang's map location?

**Comment by zfisch** [comment]
> Is something out of sync, such that Alisdair got Soo-Hwang's map location?

Sounds like it... probably related to the issue we had with signups that we resolved last week (also a sync issue).

@melissacline how urgent is this to resolve? I'm investigating some data issues at the moment but can address this as needed.

**Comment by zfisch** [comment]
I'm seeing a few strange things here:

1. 4 users have phone numbers that are set to USA  (note all ids below 10, so early users):

`storage.pg=# select "id", "firstName", "lastName" from users_myuser where "phone_number"='USA' order by id ASC;`

-[ RECORD 1 ]----------
id        | 2
firstName | Bryce
lastName  | Daines
-[ RECORD 2 ]----------
id        | 3
firstName | Ken
lastName  | Deutsch
-[ RECORD 3 ]----------
id        | 7
firstName | Mathew
lastName  | Barber
-[ RECORD 4 ]----------
id        | 8
firstName | Rebecca
lastName  | Mar-Heyming

2. Somehow, Alisdair Philp's latitude/longitude is incorrect in the DB, but when I create a new user with his same information, the correct lat/lon is inserted into the DB.

3. New users aren't showing up on the community page, but are correctly added to the DB with proper activation.

I'll post updates as I work through the issues.

**Comment by zfisch** [comment]
There are 45 users when incorrect locations according to the current algorithm we're using to determine location.

Looks like what happened is that if a user inputs an institution and a city/state/country and there's any difficulty determining the address from the institution (or if the address of the institution is at odds with the city/state/country) it may lead to errors.

The current algorithm works as follows:

```
var geo = new google.maps.Geocoder();
var formData = self.refs.contactForm.getFormData();
var address = "" + formData.institution + "," + formData.city + "," + formData.state + "," + formData.country;

if (address.length > 3) {
     geo.geocode({address: address}, (results, status) => {
             var loc;
              if (status === google.maps.GeocoderStatus.OK) {
                        loc = results[0].geometry.location;
                        formData.latitude = loc.lat().toString();
                        formData.longitude = loc.lng().toString();
              }
      }
}
```

A proposed fix is as follows:

1. First check the given city/state/country and try to determine address from there. If it fails, try to determine the address from the institution. If no address can be determined, enter a blank lat/lng.
2. Run an algorithm across the existing user base to reassign locations and update the DB according to this fix.

Another option would be to allow users to confirm their location, but I think this might be more work than it's worth. If a user needs to update any of their information they are able to do so through the application or they can contact us.
