### ISSUE TITLE
discrepancy between data output and data in DB

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#392]
I'm seeing some concerning discrepancies between what's in the database vs what's in the pipeline output from our first release.

For example, variant `chr13:g.32340264:C>A` is "Not Yet Classified" in the first release, but in every record of the data from the first release it's classified as "Pathogenic".

My hunch is that the original migration responsible for populating the database was using the data that we ended up throwing away rather than the actual release data from 10/21/2016.

This will require further investigation to confirm.

**Comment by zfisch** [comment]
It looks like the wrong data output was uploaded to the server to represent the first release. Thankfully, the new diff schema helped discover this.

This probably means some of the change_types are off for the second release, which isn't a big deal in and of itself, but does have pretty bad implications for the new way we process and display diff data.

The following fixes are recommended, though some shortcuts could be taken if deadlines are imminent:

1. Make sure correct data is on servers for download (matches data in DB).
2. Update change types and removed variant info as necessary.
3.  Generate diff data for UI.

As a note -- I'll have to work a little slower than usual due to packing/moving this week. Happy to share more info if it's helpful!

**Comment by melissacline** [comment]
Very nice catch!
