### ISSUE TITLE
Add a landing page to API endpoint (like ref server)

### ISSUE THREAD

**Issue by wdesouza** [BRCAChallenge/brca-exchange#427]
I am trying to access the GA4GH-based BRCA server endpoint (http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/). It seems to be not available anymore. Did the server URL changed?

The URL in [iPython][1] notebook is also not working (http://brca-exchange.org/backend/data/ga4gh/v0.6.0a7/). 

[1]: https://github.com/BD2KGenomics/brca-exchange/blob/master/website/django/data/static/python_notebook/brca-exchange.ipynb

**Comment by david4096** [comment]
Hi @Welliton309! Spotted a typo, thank you! The URL in the notebook should NOT have a `-`.

I was able to access the resource using the following curl request. Please let me know if you're successful.

```curl -X POST --data '{"referenceName": "17", "start": 1000000, "end": 121212121212, "variantSetId": "brca-hg37"}' http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/search -H "Content-Type: application/json"```

I opened #428 to fix the typo!

**Comment by Welliton309** [comment]
Thank you @david4096 I thought that the server wasn't available because I expected a landing page (my fault).

**Comment by david4096** [comment]
Ahh, yeah, that would be a nice feature if the landing page served swagger UI. The BRCA exchange does not use the same software as the reference server.

**Comment by david4096** [comment]
It involves adding a route here https://github.com/BD2KGenomics/brca-exchange/tree/master/website/django/data

And adding a view to go with it here https://github.com/BD2KGenomics/brca-exchange/blob/master/website/django/data/views.py

**Comment by david4096** [comment]
> Thank you @david4096 I thought that the server wasn't available because I expected a landing page (my fault).

Mind if I reopen to track the addition of this feature? I don't mind it being a separate issue if you like!
