### ISSUE TITLE
rubric for report versioning

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#442]
if all three of genomic coordinate, submitter, source are the same, consider it to be the same report -- track changes to other fields of that report

**Comment by melissacline** [comment]
@zfisch is this done?

**Comment by zfisch** [comment]
@melissacline we currently don't run diffs against reports -- is this something we still want to do?

**Comment by melissacline** [comment]
Yes.  If there's any data in the reports that's not in the summary view, we want to run diffs on that as well.  We should indicate, in the diff:
- if  there are any new reports,
- If the data inside a report has changed
- if any report has been deleted
The tricky thing is that the diff data on the reports will overlap with the summary level diff data.  But in the extreme, it's better if we show redundant diff data than if we miss something.

**Comment by zfisch** [comment]
Gotcha, will get started.

**Comment by zfisch** [comment]
@melissacline do we care about all reports or only clinvar and lovd in regards to versioning?

I ask because reports from some sources will be difficult to track between releases because they have no unique values, e.g.:

```
BIC	BRCA2	chr13:g.32346877:ATTACC>A	13	32346877	ATTACC	A	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	8881	-	yes	Class 5	7218del5	-	-	G	Western European	F	-	-	-	-	-	-	-	-	-	-	-	-
BIC	BRCA2	chr13:g.32346877:ATTACC>A	13	32346877	ATTACC	A	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	-	8882	-	yes	Class 5	7218del5	-	-	G	Western European	F	-	-	-	-	-	-	-	-	-	-	-	-
```

Notice that the only unique value between these two reports is the BX_ID, which is internal and only meaningful in a specific release for the purpose of detecting discarded reports and associating reports with variants. BX_ID's are not the same for the same reports in different releases.

ClinVar and LOVD both provide id's that we already have access to on the report level (SCV_ClinVar and DBID_LOVD) that can be used to identify reports across versions.

FWIW, it may be possible to pull in new fields for these sources, which would allow us to track reports between versions.
