### ISSUE TITLE
Augment publications on All Public Data Portal

### ISSUE THREAD

**Issue by maryjgoldman** [BRCAChallenge/brca-exchange#448]
George:
Why not including/adding a new data contributor field, where the ResearcherID, OpenID, or ORCHID number(s) will be recorded? Such information would help towards data sharing.

Mandy:
in relation to george's comments - researcher id is more appropriate when we get to individual level data submissions. however if we do want to go there, this is something that has to be instituted by the parent databases since they are managing the submissions to their own database.

**Comment by melissacline** [comment]
We'll be revamping all of this once Chloe's literature search results are in place.
