### ISSUE TITLE
variant with no diff showing up as changed/added info

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#458]
see http://brcaexchange.cloudapp.net/variant/37096

**Comment by strbean** [comment]
I dug around on this a bit, one thing I found is the Polyphen_Prediction
differs between the most recent version and the previous version. Current
version has Polyphen_prediction 'benign', while the previous version has
'possibly_damaging'

**Comment by zfisch** [comment]
Sure enough:

```
"chr17:g.43070959:A>G": [
    {
      "field": "Polyphen_Score",
      "removed": "0.546",
      "added": "0.003",
      "field_type": "individual"
    },
    {
      "field": "Polyphen_Prediction",
      "removed": "possibly_damaging",
      "added": "benign",
      "field_type": "individual"
    }
```

Currently exploring why it doesn't show in the diff.

**Comment by zfisch** [comment]
polyphen score not showing is due to typo, Polyphen_Prediction is not included in `researchModeColumns` at all -- @melissacline @maryjgoldman is there a reason this is not included and should we ignore it in the diff as well?

**Comment by zfisch** [comment]
per melissa's suggestion: hide polyphen_score and polyphen_prediction from UI, ignore in releasediff.py

**Comment by zfisch** [comment]
rerun releasediff to produce updated data since most changed/updated variants are due to polyphen_score changes
