### ISSUE TITLE
some variants are not making their way from built_with_change_types.tsv into the DB

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#468]
see NM_000059.3:c.6418_7419del14500 for an example. it's in release 6 built.tsv but not the db.

**Comment by zfisch** [comment]
requires a little more looking into, but i think the issue is actually that the variant has no change_type and is therefore not added to the new release (we currently don't add identical versions of variants to the db, we just refer to the existing one). This is fine in and of itself, except that it's excluded from the searching algorithm on the homepage.

**Comment by melissacline** [comment]
@zfisch Is this still an issue?  The variant in question now appears on the site.  According to version history, it's been there since Nov 2016, and was updated in May and October 2016.
