### ISSUE TITLE
different fields display on search table depending on user actions

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#471]
Genomic Coordinates are displayed inconsistently on the search table.

To recreate:

1. Search for a variant on the homepage. Notice Genomic Coordinate shows in the variant table.

2. Click "show expert review data". Genomic coordinate no longer shows.

3. Click "show all public data". Genomic coordinate still does not show.

What are the desired fields for the variant table for expert and all data views?

**Comment by melissacline** [comment]
I see what you describe when I open a new web browser tab and go to brcaexchange.cloudapp.net.  I don't see it when I move between the home page and the variants page within one session.

For the expert-reviewed portal, the variant table displays a fixed set of fields which does not include the genomic coordinate.  For the all public data portal, there is a default set of fields (and I don't remember if it includes the genomic coordinate or not), which are set under the confusingly-named "Show Filters" button and stored in the cookies.  Or should be.

I think the storing of the selected fields has gotten thrown off.  Here's what I'm seeing.
1. At the moment, my selected fields includes Allele Frequency but not Genomic Coordinate (GRCh38).  When I first go to the Variants page under All Public Data, I see Allele Frequency but not GRCh38.
2. When I click on Show Filters, de-select Allele Frequency, select GRCh38, and click Hide Filters, I see GRCh38 but not Allele Frequency.
3. When I select Expert Reviewed, and then select All Public Data, I once again see GRCh38 but not Allele Frequency.  It's somehow getting reset when one moves between portals, but not when one leaves the page (e.g. to go to the Community Pages).

**Comment by zfisch** [comment]
I'm a little confused -- it sounds like your selection is maintained as you switch portals (allele frequency is hidden and grch38 is shown in both portals after making the selection in your description above).

**Comment by melissacline** [comment]
This works now.  About six months ago, Zack cleaned up the field selection to make consistent use of the cookies when selecting columns for display and displaying the selected columns
