### ISSUE TITLE
False positive search result?

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#476]
From an external user:

"When I was trying to make a search for a specific BRCA2 variant, c.7895C>G, I also got a hit on c.7668_7669insA in addition to c.7895C>G.
I also tried to do a search for neighboring variants, and typed inn c.7896. The results I got was c.7669G>A, which is far off. None of the exemplified variants here have the associated BIC nomenclature to explain why they would show up in this search."

I'm seeing that when I search on "c.7895", then I also get c.7668_7669insA, but I don't get it when I search on "c.7895C>G".  Note that c.7668_7669insA has a BIC designation of 7896insA, which could in part explain why it's getting associated with the position 7895.

**Comment by zfisch** [comment]
@melissacline there is no technical issue here, but it's possible a design change is required if this behavior is incorrect.

`When I was trying to make a search for a specific BRCA2 variant, c.7895C>G, I also got a hit on c.7668_7669insA in addition to c.7895C>G.`

I'm not seeing this. Only the correct variant is returned.

`I also tried to do a search for neighboring variants, and typed inn c.7896. The results I got was c.7669G>A, which is far off.`

This variant matches on the synonym U43746.1:c.7896G>A. If this is in fact incorrect, there's either an issue with the data we receive or an issue with the way we're assigning synonyms.

`I'm seeing that when I search on "c.7895", then I also get c.7668_7669insA, but I don't get it when I search on "c.7895C>G". Note that c.7668_7669insA has a BIC designation of 7896insA, which could in part explain why it's getting associated with the position 7895.`

c.7668_7669insA has the synonym value `7896insA,p.Ala2557fs,U43746.1:c.7895_7896insA`. Note that "c.7895C>G" is not included in the synonym value so searching for it will not return the variant, but "c.7895 is in the synonym value (i.e. it's a substring). If this behavior is incorrect, we'll need to discuss how best to resolve it.

**Comment by melissacline** [comment]
@zfisch I see what's going on. "c.7895c>g" gets the one correct hit, while "c.7895" gets two hits.  The second is a bona fide synonym hit.  We made a design decision at one point to not give any visibility to the synonyms.  I suspect we need to revisit the decision - especially if we're saying that a search matched on a synonym, let's let the user see just what it's matching.  

So it sounds like the code is behaving correctly, we just need to (better) communicate that it's behaving correctly.

**Comment by zfisch** [comment]
Agreed!

It seems like somehow denoting that a variant is a synonym match in the table would be a first step (e.g. highlighting it somehow). Then on the variant detail page showing the synonyms somewhere so the circle is complete.
