### ISSUE TITLE
Community page cleanups

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#478]
Two special UI cleanups have been requested:
1. Enlarge the map, perhaps to scale with the width of the content below.  In the past, we'd had specific feedback to make the map smaller, but now that more members have signed up, we arguably need to make it bigger for better resolution.
2. Somewhere, indicate the number of members who have signed up.  Perhaps, next to the controls, show some text such as "1-10 out of 50,000"

**Comment by falquaddoomi** [comment]
Should the map retain its aspect ratio (i.e. grow vertically) as it scales horizontally? Giving it a fixed (perhaps slightly larger) vertical size and having it stretch only horizontally is somewhat easier to implement.
