### ISSUE TITLE
per report UI view

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#512]

**Comment by falquaddoomi** [comment]
Commit f31f8daa4779455c69f8f2b3b7e8d095c0187f44 introduces (hopefully?) properly-formatted fields to the reports section. Fields that have no registered display label are displayed as "?:<field>", which causes the column to overflow for particularly long ones, but there shouldn't be any of these left when the feature is completed.

Other things that remain to be done:

- Determining where to find the submitter value reliably across different sources
- Adding star ratings for each submission
- Displaying summary data in the report's header when it's collapsed
- Determining which columns from the reports should be displayed in the output
- Possibly adding controls for toggling all report visibility, or toggling on a per-source basis

**Comment by zfisch** [comment]
@melissacline @falquaddoomi 

We should figure out how to handle links to the help page -- as faisal pointed out to me, each field in the per submission tiles links to the top of the help page but the field may not be included anywhere on the help page. Additionally the per submission tiles are the only tiles without question mark links in the upper right corner of the tile.

A couple options:

1. Remove links from all per submission fields until we have a chance to determine which ones we want.
2. Remove links from all per submission fields that aren't on the help pages, hook up the ones that are.
3. Determine which fields should have help content, update help content and links for those fields.

Thoughts?

**Comment by melissacline** [comment]
My leaning is toward Option 3.  Amy has the first cut of the help pages in good shape for the expert-reviewed portal, and it's a good time for her to start looking at the all public data portal (which the GCs will be using frequently, so her focus groups would apply well here).  When I talk to her tomorrow, we'll talk about starting to do this.

**Comment by melissacline** [comment]
Just to follow up, it will probably be a few weeks before Amy can get to this.  So if it's not too late to do #2 for now, let's do that now and plan that Amy will do a more comprehensive update in a month or so.

**Comment by zfisch** [comment]
@falquaddoomi Will you have time to implement this?

> Remove links from all per submission fields that aren't on the help pages, hook up the ones that are.

**Comment by falquaddoomi** [comment]
Sure thing. So far I've added an extra prop to the per-report meta, "helpKey", that explicitly specifies which ID to scroll to when the field label is clicked. If "helpKey" unspecified, then the field label renders without an underline and help icon on hover.

I've noticed on attempting to hook up the fields that there are multiple help entries with the same ID, e.g. "Clinical Significance (ClinVar)" occurring under both "Column Groups" and "Significance" -- both have the ID "clinical-significance-clinvar" which makes it impossible to link to the second one. I've tried to see if there's a way to customize the header ID regardless of the text, but it appears that it isn't possible in vanilla markdown. We could (should?) consider writing a custom preprocessor to deduplicate the header IDs. It appears there already is some custom preprocessing going on in `loaders/markdown-id-headers.js` although I'm unsure of what it's doing...

Alternatively, I can simply leave "helpKey" unset for now and we can hook up the entries once the new documentation is in. Reports are only visible in the research portal, so this probably has low impact on people who already understand the data.

**Comment by melissacline** [comment]
Looking at Help on production, I see what you're talking about with Column Groups, which seems outdated.  I don't remember what that was supposed to be.  It's going away with Amy's new documentation.  We'll still have to link up the IDs in her documentation, but at least the multiple mapping problem is going away.

**Comment by melissacline** [comment]
Closing, to be continued as #780 and #781.
