### ISSUE TITLE
Malformed ID causes 500

### ISSUE THREAD

**Issue by david4096** [BRCAChallenge/brca-exchange#517]
When accessing a GET request by ID using the GA4GH API, if the ID does not include the variantSetId, a 500 is thrown as opposed to a 404.

http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/hg37-31353
http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/31353

**Comment by melissacline** [comment]
This now returns a 404.
