### ISSUE TITLE
Some variants cause 500 Error

### ISSUE THREAD

**Issue by david4096** [BRCAChallenge/brca-exchange#518]
This variant appears to cause a parsing error when being gathered from the database.
```
curl -X POST http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/search --data '{"referenceName": "chr13", "variantSetId": "brca-hg37", "start": 32911132, "end": 32911134}'
```

@almussel based on your analysis above it definitely seems like a specific variant is causing some parsing problem. To test this, I searched for the variant that is in the "danger zone" of your query and found this one:

http://brcaexchange.org/variant/31353

To give myself the confidence it was the one I was missing I found the variant before:

http://brcaexchange.org/variant/1773

And after:

http://brcaexchange.org/variant/13756

Finally, you can see that there is some specific variant that we are failing to handle properly http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/hg37-1773 vs http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/hg37-31353

**Comment by melissacline** [comment]
This seems to be working now.
