### ISSUE TITLE
Update the ESP allele frequency data

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#527]
- break the single field into three fields 
  * EA Allele Frequency (ESP)
  * AA Allele Frequency (ESP)
  * Allele Frequency (ESP)
- For each entry, divide the numbers by 100 to convert the percentages to fractions
- Replace the current % Allele Frequencies: EA|AA|All (ESP) with these three fields

**Comment by melissacline** [comment]
This will also impact selectAlleleFrequency and selectMaxAlleleFrequency in aggregate_across_columns.py

**Comment by zfisch** [comment]
Should the reports contain the data as provided by ESP (i.e. the combined MAF field with up to three values), or should it have the three values split up into separate fields?

**Comment by melissacline** [comment]
Let's split the three values into three separate fields.

**Comment by zfisch** [comment]
👍
