### ISSUE TITLE
The count breakdowns are off in the lollipop charts

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#529]
When I use the source selection to filter the ENIGMA variants, it returns 4932 total.  Filtering further by gene returns 2257 for BRCA1 and 2675 for BRCA2.  But the legend of the lollipop chart shows 2255 for BRCA1 (1666 pathogenic + 589 benign) and 2673 for BRCA2 (2063 pathogenic + 610 benign).  Are we losing one variant per classification and gene?

**Comment by zfisch** [comment]
> There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors. 😆 

I'll take a look!

**Comment by zfisch** [comment]
Looks like it's a timing issue -- if you deselect/select filters before the new data is loaded properly, the lollipop chart gets out of sync with the variant table. Working on a fix...
