### ISSUE TITLE
"Something went wrong" with Google Maps

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#532]
Lena is reporting a "Something went wrong" on the Community Pages, both on Chrome and Firefox.

![unnamed](https://cloud.githubusercontent.com/assets/1714823/26744512/25439644-479b-11e7-91d6-4ee1c03229fd.png)

**Comment by melissacline** [comment]
@zfisch Did we ever get any resolution on this?

**Comment by zfisch** [comment]
@melissacline nope, i'll follow up with Lena right now, but I haven't seen or heard of the issue since her report.

**Comment by melissacline** [comment]
Closing.  This seems like a transient fluke.
