### ISSUE TITLE
Variant search bug, and new test case for unit testing

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#538]
From Heidi Rehm:
"I was just trying out the BRCA Exchange website with some variants that Myriad sent directly to patients from the ACLU lawsuit and discovered a challenge. You can’t search for “p.Ala1199Val” if the entry is formatted as “p.(Ala1199Val)”. Ideally it should search with and without parentheses."

I've added this (with and without parens) to the list of search terms that should be hit, in the  [document](https://docs.google.com/document/d/1h6MvbxkJT0ekhynajeJbrlzDVwOXz0U0f4KxVx0ZK-k/edit?usp=sharing) with target variant searches.

**Comment by melissacline** [comment]
@zfisch @collinabidi One more question just like the last one: where does this stand now?

**Comment by zfisch** [comment]
@melissacline this functionality hasn't been addressed in the tests or code yet
