### ISSUE TITLE
One more search bug and unit testing test cases

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#539]
Also from Heidi Rehm:
"Also, I entered genomic coordinates as Myriad provided and did not get a hit because they didn’t include the g. . They provide “chr17:41243952” instead of “chr17:g.41243952:G>A”. The later would be solved by just adding a search example the same way you give gene name and cDNA nomenclature examples"

I've added these to the [document](https://docs.google.com/document/d/1h6MvbxkJT0ekhynajeJbrlzDVwOXz0U0f4KxVx0ZK-k/edit?usp=sharing) on target search terms.

**Comment by melissacline** [comment]
@zfisch @collinabidi  Where does this stand now?

**Comment by zfisch** [comment]
@melissacline This issue hasn't been addressed in the tests or the code yet.
