### ISSUE TITLE
logo shifts on some pages

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#551]
on beta, see variants page, scroll though other pages. unable to reproduce locally...

**Comment by falquaddoomi** [comment]
I'm having trouble reproducing the bug on the beta site, too. What does the shift look like, and what were your window dimensions when it occurred?

**Comment by zfisch** [comment]
Turns out this is due to the addition/removal of a vertical scrollbar which is a setting in some browsers. Closing since this is not an implementation issue.
