### ISSUE TITLE
logo wraps incorrectly at higher magnifications/lower window widths

### ISSUE THREAD

**Issue by falquaddoomi** [BRCAChallenge/brca-exchange#555]
The current logo wraps incorrectly when the width of the page is low and magnification is anywhere above 100%.

![image](https://user-images.githubusercontent.com/312923/27601906-36584486-5b71-11e7-853a-ec6585a2559b.png)

**Comment by melissacline** [comment]
Tested on 1/3/18 on Chrome.  Has not fixed itself, sadly.
