### ISSUE TITLE
release cleanup issues

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#566]
- in the Allele Frequency field, ExAC Minus TCGA appears as ExAC

- Include ExAC subpopulations in max allele frequency

- Make max allele frequencya default column rather than allele frequency

 (computed over subpopulations in ESP, 1000 Genomes, ExAC minus TCGA)

- in diff, allele counts appear as floating point numbers

- in built.tsv, the overall ESP column appears as Allele_Frequency_ESP, which doesn't reflect that it contains percentages rather than fractions.

- in built.tsv, the ExAC allele frequencies aren't rounded.  Is this an issue?

- likewise in added_data.tsv

**Comment by zfisch** [comment]
@melissacline 
> in the Allele Frequency field, ExAC Minus TCGA appears as ExAC
Is this referring specifically to the data itself? For example, in the diff for the november release for the following variant where it reads "Allele Frequency: 0.0002965 (ExAC))  0.0002542 (ExAC))"?
http://brcaexchange.org/variant/43544

**Comment by melissacline** [comment]
Yes, that's exactly what I was referring to.
