### ISSUE TITLE
Update the source code link in the footer

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#573]
The Source Code link in the footer of the web portal points to the old GitHub repo, https://github.com/BD2KGenomics/brca-website.  This should be updated to point to the new repo, https://github.com/BRCAChallenge/brca-exchange.

**Comment by izcram** [comment]
@zfisch shall I take this and make a PR? Seems easy enough as a starter ;)

**Comment by zfisch** [comment]
@izcram sure! thanks.
