### ISSUE TITLE
Internal Server Error (500) when querying the BRCA1 region in Chromosome 17

### ISSUE THREAD

**Issue by diegollarrull** [BRCAChallenge/brca-exchange#587]
Hello,

when querying the entire region covered by the BRCA1 gene in Chromosome 17, the server returns a **500** error. My guess is that processing (at least) one of the found variants causes the server to crash. Here are the API requests, both for **hg37**:

`curl -X POST http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/search --data '{"referenceName": "chr17", "variantSetId": "brca-hg37", "start": 41196312, "end": 41322420}'`

and **hg38**:

`curl -X POST http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/search --data '{"referenceName": "chr17", "variantSetId": "brca-hg38", "start": 43045629, "end": 43125483}'`

(_Start_ and _End_ values gathered from [here](http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr17%3A41196312-41277500&hgsid=601974927_EieXjKb6jIyCEoknySiGQhDX17g8) and [here](http://genome.ucsc.edu/cgi-bin/hgGene?hgg_gene=uc002ict.4&hgg_prot=ENST00000471181.6&hgg_chrom=chr17&hgg_start=43045628&hgg_end=43125483&hgg_type=knownGene&db=hg38&hgsid=601974927_EieXjKb6jIyCEoknySiGQhDX17g8)).

Note that the query in the notebook example, which searches in a smaller region in **hg37**, works just fine:

`curl -X POST http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7/variants/search --data '{"referenceName": "chr17", "variantSetId": "brca-hg37", "start": 41246794, "end": 41296814}'`

Thank you very much for your help.

**Comment by david4096** [comment]
Thanks @diegollarrull we have seen something like this in the past! You're right likely a string coercion problem.

@zfisch related? https://github.com/BRCAChallenge/brca-exchange/commit/d13055f0b3de014a29e83c677b51e369386204e8

**Comment by melissacline** [comment]
This appears to be working now.  I'm closing the issue until someone brings it up again.
