### ISSUE TITLE
Incorrect BRCA1 genomic ranges for 1000 Genomes

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#618]
As pointed out by Michael Parsons, BRCA Exchange currently contains a number of variants  that upstream of BRCA1, but so far upstream that they would not be considered part of BRCA1.  These turn out to be 1000 Genomes variants.  It turns out that when variants are selected from the 1000 Genomes VCF file (by genomic coordinate), the range is too wide.  The range being used is chr17:41191488-41322420.  The more appropriate range would be chr17:41196312-41277500 (from Entrez, https://www.ncbi.nlm.nih.gov/gene/672).

**Comment by zfisch** [comment]
@melissacline  Has this been resolved?

**Comment by melissacline** [comment]
Yes, that was resolved in the September release
