### ISSUE TITLE
include attribution links to ClinVar and LOVD variants

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#619]

**Comment by melissacline** [comment]
The formula for linking to ClinVar with SCV accessions is detailed [here](https://www.ncbi.nlm.nih.gov/clinvar/docs/linking/).  For example, for the accession SCV000321149.1, the URL would be http://www.ncbi.nlm.nih.gov/clinvar/?term=SCV000321149.1
