### ISSUE TITLE
Small Displays: close nav menu dropdown after navigation

### ISSUE THREAD

**Issue by strbean** [BRCAChallenge/brca-exchange#63]

**Comment by falquaddoomi** [comment]
According to BD2KGenomics/brca-exchange#28 this is still waiting for a fix from the react-bootstrap people? I could hack around it, but judging from the previous discussion I'm not sure that's desired.

**Comment by melissacline** [comment]
With the mobile app, small display issues with react-bootstrap are less of a priority, and not worth hacking around.
