### ISSUE TITLE
automate creation of directory for data deploy

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#630]

**Comment by izcram** [comment]
I think it would make most sense to tweak `deploy-data`, s.t. only the release archive gets uploaded to the deployment host and the necessary files are extracted there. WDYT @zfisch?

**Comment by zfisch** [comment]
Excellent idea!

**Comment by melissacline** [comment]
@izcram @zfisch Where does this stand?

**Comment by melissacline** [comment]
@zfisch @izcram I see that this issue is marked as Ready for QA.  Can it be closed, or is it still in process?  Thanks!

**Comment by zfisch** [comment]
This is complete!
