### ISSUE TITLE
automate update of trackhubs for UCSC genome browser after data-deploy

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#631]

**Comment by zfisch** [comment]
see pipeline/genomeBrowserTrack/readme.md for details

**Comment by izcram** [comment]
Did you have in mind to put the steps in the readme.md into a script and then call it from `deploy-data` script?

**Comment by zfisch** [comment]
Yep! Seems like the best way to go, keeps everything self contained.
