### ISSUE TITLE
NP Identifiers Not Displayed in "Protein Identifier" Field (Expert Reviewed)

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#655]
Variants who have NP Protein Identifiers do not display this field on the Variant Details Page, even though it is searchable within the database. 

To reproduce this issue, search "NP_009225.1:p.(Leu358CysfsTer16)". 
Click the variant result to view its Variant Details Page. 
Make sure Empty Items are displayed. 
Note that Protein Identifier still appears to be a blank field, even though its NP is in the database and can be used to search the variant.

**Comment by melissacline** [comment]
Zack, would you look into this?  If we don't have the data in our pipeline, we should be able to get it pretty easily.

**Comment by zfisch** [comment]
To clarify, "Protein Identifier" is not currently a field in the output or a column in the database (therefore no matter what type of "protein identifier" a variant has, it will never be displayed). 

If users are already able to search by it, is there additional value to creating a new field for it and displaying it, or is it already obvious from existing fields? If we do want it, how can I determine it and where do we want it displayed?

**Comment by melissacline** [comment]
The "Protein Identifier" should be the portion before the colon in the pyhgvs_Protein field.  For example, given a pyhgvs_Protein string of NP_000050.2:p.?, the Protein Identifier should be NP_000050.2.
