### ISSUE TITLE
fix any issues in deploy-data, currently throws error when run with "local" as environment

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#661]
Error: ./deployment/deploy-data: line 98: unexpected EOF while looking for matching `"'

**Comment by zfisch** [comment]
Error: `./deployment/deploy-data: line 98: unexpected EOF while looking for matching `"'`

**Comment by izcram** [comment]
Cannot reproduce. Is this still an issue with the current version?

**Comment by zfisch** [comment]
also can't reproduce... closing.
