### ISSUE TITLE
ensure ansible scripts are set up properly after move to brcachallenge repo

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#663]
coordinate with @melissacline as needed. might not require any work at all except a check and thumbs up

**Comment by izcram** [comment]
Current status: To better test those ansible scripts and also to facilitate the creation of a local development environment, I'm working on adding the possibility to easily create a local virtual machine using vagrant. On the way, I've found some small details regarding apache modules which were out of sync with the ansible scripts (some apache config has most likely been tweaked manually).
PR of this work will follow soon on the appropriate repo.
After that, I'll attempt to reprovision our productive server using the ansible scripts.

**Comment by zfisch** [comment]
@izcram what's the status on this?

**Comment by izcram** [comment]
there is a PR pending here https://github.com/BRCAChallenge/brca-configuration/pull/2 . once I get some feedback there I'll attempt to run it on a dev machine and then on prod
