### ISSUE TITLE
Figure out how to make software releases to link to in release notes for each data release.

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#666]
basically we want a link to a version of the software used to generate a data release when the data pipeline is run

**Comment by zfisch** [comment]
@izcram checking in on this issue

**Comment by zfisch** [comment]
@izcram what's the status on this?

**Comment by izcram** [comment]
I think this is resolved. Starting with the February 2018 release we tag the corresponding git commit used with 'data_release_%y_%M_%d'. Also the docker image gets published to dockerhub since then.
