### ISSUE TITLE
Adding rs identifiers to the annotation

### ISSUE THREAD

**Issue by david4096** [BRCAChallenge/brca-exchange#67]
I may be reading incorrectly, but are `rs-` identifiers available as an annotation? Does it make sense to allow one to search by rs number in the magic search box 🎱? I imagine these values are available for some of the variants, however, it appears they are not available in the annotation currently.

I believe this would require a modification to the pipeline with a column for rsid's and the addition of a field to the variant model.

**Comment by melissacline** [comment]
The dbSNP IDs aren't currently available as an annotation, but adding them sounds like a great idea!  I'll add that as a feature request.

**Comment by melissacline** [comment]
This is an enhancement that hasn't been getting any demand.
