### ISSUE TITLE
variants submitted by bic / enigma are not always showing up in clinvar

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#671]
https://docs.google.com/a/ucsc.edu/spreadsheets/d/1FG2lJpngKRUYpm6K9kIAb9o4bX6mQ33LpssuFL-pVcE/edit?usp=sharing

https://docs.google.com/a/ucsc.edu/spreadsheets/d/1G_tqmyqVB9IuBZVMe0nMSVpNQn4xEJrrID_B_SwoITQ/edit?usp=sharing

**Comment by melissacline** [comment]
From Charlie:

So below are the list of variants that I've tried to cross-reference against various other sources. The variants can all be found in the "
BIC.no.ClinVar.tsv" file from the release tar file. The main thing I see in the BRCA2 variants is that the HGVS CDNA variant is listed differently from that of the HGVS Genomic variant fields. I'm guessing this discrepancy is probably what led to ClinVar from removing those variants from the BIC submission to ClinVar. You can also observe this difference between the HGVS ID field and the actual REF and ALT allele fields in the "BIC.vcf" file in the BRCA exchange pipeline output.

As for BRCA1 variants, I'm not sure yet. That last variant I list in the notes below is present in the raw ClinVar file and I believe it should be included in the final output of the BRCA exchange pipeline, but for some reason it's not. I don't know yet if the other BRCA1 variants also show this pattern.



Attached are the files which I have cross referenced these variants with:

-- "BIC.no.ClinVar.tsv": The main BRCA exchange diff file between the BRCA exchange BIC and ClinVar scrapped variants.

-- "brca1_data_BIC_RAW_dataset.txt": The raw dataset of BIC BRCA1 variants obtained directly from the BIC database. Can get the file by clicking the "download" button on this page (https://research.nhgri.nih.gov/projects/bic/Member/brca1_mutation_database.shtml)

-- "brca2_data_BIC_RAW_dataset.txt": The raw dataset of BIC BRCA2 variants obtained directly from the BIC database. Can get the file by clicking the "download" button on this page (https://research.nhgri.nih.gov/projects/bic/Member/brca2_mutation_database.shtml)

-- "clinvar_result_BIC_BRCA1.txt": The raw dataset of ClinVar BRCA1 data obtained from the ClinVar database. Can get the file by clicking the "download" button on the lower right-hand corner of this page (https://www.ncbi.nlm.nih.gov/clinvar/?LinkName=orgtrack_clinvar&from_uid=504196)

-- "clinvar_result_BIC_BRCA2.txt": The raw dataset of ClinVar BRCA2 data obtained from the ClinVar database. Can get the file by clicking the "download" button on the lower right-hand corner of this page (https://www.ncbi.nlm.nih.gov/clinvar/?LinkName=orgtrack_clinvar&from_uid=504197)

-- "BIC.vcf": The BIC vcf located in the BRCA exchange release tar file under the "artifacts" directory.

-- "ClinVarBrca.vcf": The ClinVar vcf located in the BRCA exchange release tar file. 

My notes are as follows:

## BIC     13      32316409        T       G    (according to "BIC.no.ClinVar.tsv")
#	("BIC.no.ClinVar.tsv") On BRCA Exchange pipeline output, HGVS GDNA is listed as a T>G mutation. HGVS CDNA is dependant on reference used (IVS1-13A>G,IVS1-13A>G,U43746.1:c.189-13T>G)
#	("brca2_data_BIC_RAW_dataset.txt") On BIC Raw dataset, HGVS CDNA is c.-39-13A>G while GDNA is g.32890546T>G and BASE_CHANGE field is stated to be A to G.
#	("clinvar_result_BIC_BRCA2.txt") On ClinVar dataset, the variant isn't listed.
#	("BIC.vcf") On BRCA Exchange pipeline BIC dataset, REF (T) and ALT (G) is different from the ID field (NM_000059.3:c.-39-13A>G)

## BIC     13      32316676        C       G    (according to "BIC.no.ClinVar.tsv")
#	("BIC.no.ClinVar.tsv") On BRCA Exchange pipeline output, HGVS GDNA is listed as a C>G mutation. HGVS CDNA is dependant on reference used (IVS2+149T>G,IVS2+149T>G,U43746.1:c.294+149C>G)
#	("brca2_data_BIC_RAW_dataset.txt") On BIC Raw dataset, HGVS CDNA is c.67+149T>G while GDNA is g.32890813C>G and BASE_CHANGE field is T to G.
#	("clinvar_result_BIC_BRCA2.txt") On ClinVar dataset, that variant isn't listed.
#	("BIC.vcf") On BRCA Exchange pipeline BIC dataset, REF (C) and ALT (G) is different from the ID field (NM_000059.3:c.67+149T>G)

## BIC     13      32326017        G       C    (according to "BIC.no.ClinVar.tsv")
#	("BIC.no.ClinVar.tsv") On BRCA Exchange pipeline output, HGVS GDNA is listed as a G>C mutation. HGVS CDNA is dependant on reference used (IVS4-84T>C,IVS4-84T>C,U43746.1:c.653-84G>C)
#	("brca2_data_BIC_RAW_dataset.txt") On BIC Raw dataset, HGVS CDNA is c.426-84T>C while GDNA is g.32900154G>C and BASE_CHANGE field is T to C.
#	("clinvar_result_BIC_BRCA2.txt") On ClinVar dataset, that variant isn't listed.
#	("BIC.vcf") On BRCA Exchange pipeline BIC dataset, REF (G) and ALT (C) is different from the ID field (NM_000059.3:c.426-84T>C)

## BIC     17      43124098        T       A    (according to "BIC.no.ClinVar.tsv")
#	("BIC.no.ClinVar.tsv") On BRCA Exchange pipeline output, HGVS GDNA is listed as a T>A mutation. HGVS CDNA is dependant on reference used (118A>T,118A>T,NM_007294.2:c.-2A>T,NM_007300.3:c.-2A>T,NM_007299.3:c.-2A>T,NM_007298.3:c.-2A>T,NM_007297.3:c.-89A>T,U14680.1:c.111A>T)
#	("brca1_data_BIC_RAW_dataset.txt") On BIC Raw dataset, HGVS CDNA is c.-2A>T while GDNA is g.41276115T>A and BASE_CHANGE field is A to T.
#	("clinvar_result_BIC_BRCA1.txt") On ClinVar dataset, the variant IS present on line 1743 of "clinvar_result_BIC_BRCA1.txt"
#	("BIC.vcf") On BRCA Exchange pipeline BIC dataset, the variant IS present on line 29038
#	("ClinVarBrca.vcf") On BRCA Exchange pipeline, the variant is NOT present. Should be between lines 35682 and 35683.

[BIC_cross_refence_files.zip](https://github.com/BRCAChallenge/brca-exchange/files/1569756/BIC_cross_refence_files.zip)

**Comment by melissacline** [comment]
Looking more closely at some of these BIC variants:
U43746.1:c.189-13T>G a.ka. IVS1-13A>G appears in ClinVar as U43746.1:n.190-13A>G (which did not pass HGVS validation), at https://www.ncbi.nlm.nih.gov/clinvar/variation/125954/.  ClinVar reports it, but in the perfect case it shouldn't.  As Charlie points out, the reference base has changed.  There are no submissions of this variant other than the BIC submission.  How could we filter out this variant in the next release?

(118A>T,118A>T,NM_007294.2:c.-2A>T,NM_007300.3:c.-2A>T,NM_007299.3:c.-2A>T,NM_007298.3:c.-2A>T,NM_007297.3:c.-89A>T,U14680.1:c.111A>T): In ClinVar at https://www.ncbi.nlm.nih.gov/clinvar/variation/125485/.  hg19 and hg38 show the variant as T>A (i.e. a T in the reference position, rather than an A).  This appears to be an old, noisy variant that we should be filtering out.

So it really looks like we're doing the right thing by filtering out the ClinVar reports of these variants, but how can we filter out the BIC reports of the same variant?

**Comment by cmarkello** [comment]
@melissacline Could we just simply take the variants reported in "BIC.no.ClinVar.tsv" and leave them out of the BIC dataset. Although in that case BIC would then become a proper subset of ClinVar and thus the BIC dataset may not need to be included at all unless people needed source information on those variants.

**Comment by melissacline** [comment]
@cmarkello That sounds reasonable.

**Comment by zfisch** [comment]
@melissacline checking in on this issue -- it seems like we left off at a place where we're deciding whether to exclude BIC variants not found in clinvar from the BIC dataset. Charlie pointed out that if we do this it makes the BIC dataset redundant -- how would you like us to proceed?

**Comment by zfisch** [comment]
@cmarkello 

Note: on a recent call we discussed that there are potentially good variants in BIC that are not in ClinVar, so we shouldn't filter out any variants not found in ClinVar.

We'll need to use another method to determine which variants should or shouldn't be filtered out of BIC.

**Comment by cmarkello** [comment]
@zfisch 
I'm on the call so I heard a little bit of the conversation. I took a quick look at my notes again to jog my memory. So the problem is that a lot of the variants that are in BIC but not in ClinVar have those conflicting HGVS variants. After checking with the UCSC genome browser it definitely looks like the more modern transcript HGVS representations are the more accurate versions of those variants. I'm not sure what the best action would be to take on these variants.

**Comment by melissacline** [comment]
To wrap up this issue, these are variants for which the reference base no longer matches what's in the reference human genome, so we're filtering these out deliberately.

**Comment by cmarkello** [comment]
Sorry this issue got dragged out. I got distracted by duties on the VG team
and lost track of this problem. I couldn't find an immediate solution as to
how to handle these ambiguous variants. I think filtering out variants with
ambiguous mappings to old reference positions is a good call. We don't want
to include any ambiguous data in the dataset if possible.

-Charlie
