### ISSUE TITLE
BIC accession id's need to be updated

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#672]

**Comment by melissacline** [comment]
What's this?

**Comment by melissacline** [comment]
@cmarkello @zfisch Is this issue still being worked on?

**Comment by melissacline** [comment]
@cmarkello Is this part of #671  or is it a separate issue?

**Comment by cmarkello** [comment]
@melissacline This issue was resolved and the branch was merged. I must have forgotten that I had left this issue open. Permission to close?
