### ISSUE TITLE
website blocked by firewall?

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#676]
I’m also working on getting the BRCAExchange website working here, it was initially blocked by IT, now it’s unblocked and I can search but clicking any variant gives me a blank page. This will be a local IT issue but obviously I want to get it fixed so all my colleagues can use it. It means I can’t give you very useful feedback at the moment though!

from Clinical Genetics | Box 134 | Cambridge University Hospitals NHS Foundation Trust 
Addenbrooke's Hospital | Hills Road | Cambridge | CB2 0QQ

**Comment by melissacline** [comment]
Closing until we're in a position to address this concretely.
