### ISSUE TITLE
create faq page

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#683]

**Comment by melissacline** [comment]
Looking at Amy's sandbox at http://104.210.44.242:8080/, the functionality is there but the FAQ (and the help page, for that matter) could use some styling.  @falquaddoomi would you take a look?

**Comment by falquaddoomi** [comment]
@melissacline Sure thing. Am I correct in thinking that this work is in the 'faq' branch? If so, I'll go ahead and branch from it, make some edits, and submit a pull request.

**Comment by melissacline** [comment]
Thanks, Faisal!  @zfisch just to verify, is this the faq branch?  @amycoffin here's a heads-up that your faq and help pages are about to get some styling.

**Comment by zfisch** [comment]
@falquaddoomi @melissacline yep!
