### ISSUE TITLE
adjust export_data_for_genome_browser.sh to handle relative paths

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#696]
Throws an error given a relative path:

pipeline@brcaexchange-pipeline:~/pipeline_dev_zack/brca-exchange$ sudo ./pipeline/genomeBrowserTrack/export_data_for_genome_browser.sh ../../monthly_releases/data_release_2017-12-19/brca_out/release-12-19-17.tar.gz
tar (child): ../../monthly_releases/data_release_2017-12-19/brca_out/release-12-19-17.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by zfisch** [comment]
@izcram checking in on this issue

**Comment by izcram** [comment]
@zfisch should be resolved by 6d3f104

**Comment by melissacline** [comment]
@izcram can this issue be closed now?

**Comment by izcram** [comment]
From my point of view yes
