### ISSUE TITLE
Styling, help.md/help_research.md

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#712]
There are text-size issues with sub-bullet lists in help.md and help_research.md. They are under Variant Nomenclature Tile> HGVS Nomenclature. These versions of the markdown can be found in my FAQ branch that is going to beta soon. For some reason, the text is larger than it should be. It might be due to the css not having integrated that level of bullets before.

**Comment by zfisch** [comment]
There is currently nothing on the FAQ branch or master for me to make styling changes to. Please make a PR once your changes are ready and after they're merged I can make any styling updates.
