### ISSUE TITLE
navigation items wrap to a second line when below 1200px width

### ISSUE THREAD

**Issue by falquaddoomi** [BRCAChallenge/brca-exchange#718]
As of d722d147ea8638b08f28d7a984b3b3e727ad52eb, navigation items in the header wrap to a second line when the viewport drops below 1200px width, and persist (despite the navbar branding changing layout) until 768px, when the navigation items collapse into a dropdown menu.

**Comment by falquaddoomi** [comment]
This is probably a result of adding the "FAQ" item to the navbar.

**Comment by zfisch** [comment]
Nice find, think you can put in a PR for a fix in the next day? If not I can take care of it, but want to get it before release.

**Comment by falquaddoomi** [comment]
Sure thing; I'll work on it tomorrow morning and hopefully have a fix within an hour or two.

**Comment by falquaddoomi** [comment]
Fixed in PR #720.
