### ISSUE TITLE
Fix page extending beyond borders on small screens

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#722]
I'm noticing the same behavior on the Variant Details page of the production site (http://brcaexchange.org/variant/68606) using an iPhone 8 preset w/Chrome's mobile view. It looks to me like the version history table is stretching out the page; it's 544px whereas the viewport is 375px. Part of the problem is that the date column doesn't wrap (my error, introduced a while ago when we were fixing up the look & feel), but even if that column is set to wrap it still exceeds the width.

Perhaps this should be a separate issue specifically about the page being stretched past the viewport in mobile devices, since I'm noticing this behavior on other pages as well. For instance, http://brcaexchange.org/variants?search=c.956 stretches past the viewport due to the "matching variants" textbox being too wide.

I have some ideas on how to fix these issues (hiding the "Changes" column, allowing the error text to wrap, etc.), so I'd be happy to work on it on a separate issue branch.

**Comment by falquaddoomi** [comment]
Fixed in #724.
