### ISSUE TITLE
mupit integration

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#735]
use 4 thumbnails to cover different types of variants, display accordingly when a user views the variant detail page. use api call to mupit to determine if a mupit display is relevant.

link the thumbnail to mupit for a more in-depth visualization.

**Comment by melissacline** [comment]
See the wireframes at https://docs.google.com/presentation/d/1tVXcBpoSzSTQhg1kJwifK2kwVeNy7VWzdknWPSYZyNY/edit?usp=sharing.
