### ISSUE TITLE
Mozilla Firefox: FAQ Functionality Broken

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#736]
I just got an email from a friend who I sent the brcaexchange.org link to, and he told me that the FAQs are not clickable on his Firefox browser. The menu link works, but he cannot click the questions individually.

**Comment by zfisch** [comment]
good catch! I just pushed up a fix to master that's now available on my dev server at http://brcaexchange-dev.cloudapp.net:9002/faq

It won't be available on production until after the next deployment.
