### ISSUE TITLE
Facts and Stats Changes per Mandy as of 3/6

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#744]
- update Berghofer Medical research institute to read "QIMR Berghofer Medical Research Institute"

- change "However, when either of these genes are altered by a variation in the gene sequence," to
"However, when the function of either of these genes is significantly altered by a variation in the gene sequence," (point is not all variation will lead to risk)

**Comment by rgliao** [comment]
Why is the change being made to remove the sentence referencing the outcomes from the Paris meeting? This doesn't seem necessary to me.

**Comment by amycoffin** [comment]
Mandy asked that we update it in an email about a few different pages.

**Comment by rgliao** [comment]
I would rather we didn't add/remove specific content without a more formal review, given this was developed with a fair amount of review and oversight. It's fine to update the affiliation, reword for clarity, etc. You can feel free to forward or add me to any emails if that would be helpful.

**Comment by amycoffin** [comment]
That makes total sense. For some reason I thought you were copied on that email, and assumed that no comments meant the changes were not significant. I'll definitely make sure you are copied on future emails, and we won't change this for now.

**Comment by zfisch** [comment]
@amycoffin what is the status on this ticket? What updates need to be made and what updates are being omitted following this conversation?

**Comment by amycoffin** [comment]
The changes have already been omitted and it is ready.
