### ISSUE TITLE
Column Selectors for Clinical Signficance (LOVD) and (ClinVar): Functionality and Documentation

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#756]
When clicking "Show Column Selectors" on the Variant Page, there are two tiles that have no selectors: Clinical Significance (ClinVar) and Clinical Significance (LOVD). These tiles correspond with recently updated variant details tiles. 

Once the selectors are fixed, we should update the All Public Data Help Page to reflect the column selectors accurately. Furthermore, the documentation about the new updated Variant Details Tiles needs to get done, but that is perhaps a different issue.

![Available Column Selectors](https://user-images.githubusercontent.com/25374391/37931827-b5dcda18-30fb-11e8-935b-28a465a776dc.png)

**Comment by melissacline** [comment]
@amycoffin I'd like to prioritize those two tiles for the next round of documentation, after the one that goes to the EGG next week.

**Comment by amycoffin** [comment]
@melissacline Makes sense. Should we talk about what needs to be documented at next week's 1-on-1? (Basically one of those meetings where I take notes on our conversation and use it as a starting point for a draft that goes for internal review). We may also want to discuss how to balance this DocDev with the priors DocDev, biting off appropriately sized pieces on each.

**Comment by melissacline** [comment]
Amy, let's focus on the general docdev for now, and not worry about the
priors just yet.
