### ISSUE TITLE
New wording for new Community Pages registration

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#76]

**Comment by melissacline** [comment]
When a new user registers for the Community Pages, the user sees a banner message stating: "Thanks for signing up. We have sent you an email with a confirmation link to complete your registration".  We should change this message to also alert the user that he or she will  appear on the Community Pages only after an administrator approves the registration.  Suggested wording:  "Thanks for signing up. We have sent you an email with a confirmation link to complete your registration.  After your entry is confirmed by an administrator, we will formally add you to the community".

**Comment by maryjgoldman** [comment]
How about 'After you complete your registration our administrator will confirm your profile and it will appear on the Community Pages.' ?

**Comment by melissacline** [comment]
Yes, that's better!
