### ISSUE TITLE
BIC Column Selectors Out of Date 

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#760]
The following Column Selectors need to be removed for BIC:
- Clinical Significance 
- Clinical Importance

**Comment by melissacline** [comment]
I remember the discussion now.  We made a conscious decision to remove these fields in the variant details page.  The fields were never removed from the variants page.  @zfisch would you get someone to remove these two fields from the Variants table, and from the Column Selectors menu?
