### ISSUE TITLE
ensure config.js is set to correct environment

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#764]
config.js environment property should be set to beta for all environments except production. this can be handled in the brca-configuration repo

**Comment by zfisch** [comment]
@izcram could you take this on?

inside of js/config.js there is an "environment" property that should be set to "beta" for non production versions of the site. that property can be used for many things, but currently determines whether or not to show a big red banner at the top of the screen that tells users that they're not looking at the production website. for reference, see the `isBeta` state variable in js/NavBarNew.js.

this variable could probably be set using ansible, but whatever method makes the most sense to you is fine!

**Comment by izcram** [comment]
might already have been fixed here: https://github.com/BRCAChallenge/brca-configuration/pull/2
As far as I recall, I needed to rename the variable `environment` to `environment_name` as the former was messing with ansible.
If after the PR merge it still persists, I'll have a look at it.

**Comment by zfisch** [comment]
ah yes, I'd forgotten about this -- I just sent you a message on slack regarding continued trouble running `vagrant up` -- let's see if we can get this sorted out and merged
