### ISSUE TITLE
Add the Date Last Reviewed to the ClinVar reports and tiles

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#779]
We should report ClinVar's Date Last Reviewed as a complement to the Date Last Updated.  We will need to add this to the pipeline, and to the ClinVar report tiles.

**Comment by zfisch** [comment]
@izcram could you tackle this while working on the other clinvar data and enigma pipeline updates?

**Comment by zfisch** [comment]
@izcram checking to see if this issue was addressed in the latest changes or where it currently stands

**Comment by izcram** [comment]
Yes, indeed, this was addressed in #829
