### ISSUE TITLE
look into pyhgvs_cdna doesnt match hg38 start and end

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#787]
The BRCA2 variants that I found that had Hg38 Start and End coordinates that did not match with the pyhgvs_cDNA were c.71delT (Hg38_Start=32319077 and Hg38_End=32319078 which correspond to c.68 and c.69) and c.71_96delTAGGACCAATAAGTCTTAATTGGTTT (Hg38_Start=32319077 and Hg38_End=32319103 which correspond to c.68 and c.94). Even with the RefSeq numbering potentially adding/subtracting 1 these coordinates are still off. I think there might have been one more but I can’t remember it right now

**Comment by ccdlott** [comment]
I found another one in BRCA2 c.6842-30_6842-3del28 Hg38_Start = 32344526 (c.-32) and Hg38_End = 32344554 (c.-4)
