### ISSUE TITLE
Transcript visuals not correct for some BRCA1 variants

### ISSUE THREAD

**Issue by cmarkello** [BRCAChallenge/brca-exchange#788]
@zfisch @melissacline 
I've discovered some inconsistencies when looking at a couple of BRCA1 variants in the lollipop chart and comparing that against what's displayed in the variant detail Transcript Visualizations. It seems the chromosomal positioning is incorrect.

For example:
- located in brca1 exon 10 in the lollipop chart, but located in exon 15 in the transcript visual: http://brcaexchange.org/variant/102515
- located in brca1 exon 12 in the lollipop chart, but located in exon 13 in the transcript visual: http://brcaexchange.org/variant/102709

**Comment by zfisch** [comment]
@falquaddoomi could you take a look at this?

**Comment by falquaddoomi** [comment]
Concerning; thanks for catching that, @cmarkello. I'll take a look as soon as I can.

**Comment by ccdlott** [comment]
@falquaddoomi the chromosomal positioning in the transcript visualization matches the chromosomal positioning on the HCI PRIORS website for the variants listed above

**Comment by ccdlott** [comment]
@falquaddoomi I think the issue is with the lollipop chart and not the transcript visualization. The lollipop chart does not take into account the fact the BRCA1 is a minus strand gene so variants that are in exon 1 in the lollipop chart are actually in the last exon in the visualization which is correct because these are 3' UTR variants. The opposite is also true, variants in the last exon on the lollipop chart are really in the first exon and are 5' UTR variants. There also might be an issue with the exon positioning because the lollipop visualization does not skip exon 4 and the transcript visualization does skip exon 4.

**Comment by cmarkello** [comment]
It looks like a simple modification to reverse the ordering of the exon
number labels on the brca1 lollipop domain should fix it. The JSON file
that the lollipop chart parses can be found here
https://github.com/BRCAChallenge/brca-exchange/blob/master/website/content/brca1LollipopDomain.json
.

Though after looking at it again, I'm a little unsure about the exact exon
structure of build GRCh38 BRCA1. It looks as though some of the boundary
exons are labeled as UTR's instead of as actual exons.
http://www.rcsb.org/pdb/gene/BRCA1?v=hg38
https://genecards.weizmann.ac.il/geneloc-bin/exon_struct.pl?disp_name=BRCA1&chr_nr=17

-Charlie

**Comment by melissacline** [comment]
The first exon in BRCA1 (in the canonical transcript) is a UTR exon.

If it's truly a simple thing to reorder the lollipop plot to show exons in
transcript order rather than genome order, that would be awesome!


On Fri, May 18, 2018 at 11:32 AM, Charles Markello <notifications@github.com
> wrote:

> It looks like a simple modification to reverse the ordering of the exon
> number labels on the brca1 lollipop domain should fix it. The JSON file
> that the lollipop chart parses can be found here
> https://github.com/BRCAChallenge/brca-exchange/
> blob/master/website/content/brca1LollipopDomain.json
> .
>
> Though after looking at it again, I'm a little unsure about the exact exon
> structure of build GRCh38 BRCA1. It looks as though some of the boundary
> exons are labeled as UTR's instead of as actual exons.
> http://www.rcsb.org/pdb/gene/BRCA1?v=hg38
> https://genecards.weizmann.ac.il/geneloc-bin/exon_struct.pl?
> disp_name=BRCA1&chr_nr=17
>
> -Charlie
>

**Comment by cmarkello** [comment]
@melissacline 
What's the NCBI RefSeq ID of the canonical BRCA1 transcript? There are many transcripts. NM_007300.3 is listed first in this BRCA1 transcript table (http://useast.ensembl.org/Homo_sapiens/Transcript/Exons?db=core;g=ENSG00000012048;r=17:43044295-43125370;t=ENST00000357654). NCBI lists this transcript as "transcript variant 2" while the second transcript on the list, NM_007294.3, is labeled by NCBI as "transcript variant 1". Either one of these lists a different number of exons.

Also, it looks like the transcript visuals for the BRCA1 variants list 24 exons (http://brcaexchange.org/variant/102457) while the transcript definition for NM_007294.3 is that there are 23 exons (http://useast.ensembl.org/Homo_sapiens/Transcript/Exons?db=core;g=ENSG00000012048;r=17:43044295-43125370;t=ENST00000357654)

**Comment by ccdlott** [comment]
We use NM_007294.3 and there are 23 total exons in BRCA1 but exon4 is skipped so the last exon is exon 24
