### ISSUE TITLE
intronic variant showing up as exonic in visualization

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#792]
HGVS string (c.5406+1G>A), the plus sign indicates that it's in the intron.  Any variant with either a plus or minus sign is intronic.

**Comment by zfisch** [comment]
<img width="1157" alt="screen shot 2018-05-24 at 3 03 04 pm" src="https://user-images.githubusercontent.com/4503616/40515939-b6555696-5f63-11e8-9c5d-80d29ca044a9.png">

**Comment by falquaddoomi** [comment]
Good catch. It seems that variant is at 43049120 and right on the boundary of exon 22, which starts at 43049120 and ends at 43049194 according to SplicingData.js. I guess that implies that the exon boundaries are exclusive? Also, we internally represent variants of a single nucleotide as being the interval (position, position+1); I assume we should treat that interval as inclusive for the lower bound and exclusive for the upper one, or else this variant (43049120, 43049121) would still be within exon 22.

**Comment by falquaddoomi** [comment]
After a bit of investigation, it seems that the exons for both BRCA1 and BRCA2 are exclusive in their starting position and inclusive in their ending position. I made that adjustment in the code and did some more spot-checking around the exon/intron boundaries in both genes, and it appears that variants with a +/- are being correctly rendered into introns now.
