### ISSUE TITLE
Genetic Counselor Recommendation: Data Completion Visual

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#799]
Per conversations with Genetic Counselors, create some sort of visual representation, perhaps a bar with percentages, for data completion/confidence about a variant. Melissa, you asked me to create an issue and assign it to you after the GC meetings, but it sat on my To Do list for too long.

**Comment by melissacline** [comment]
I remember this.  The EGG wasn't as enthusiastic about this suggestion.  But, let's keep it in the backlog queue, to potentially revisit in a few months.
