### ISSUE TITLE
Variant Details Page: Hover Over Definitions

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#800]
Provide hover over definitions for the variant details page that correspond with, and auto-update according to, Help Text.

**Comment by melissacline** [comment]
@falquaddoomi Have you had a chance to think more about this yet?

**Comment by falquaddoomi** [comment]
@melissacline I haven't had a chance to address it yet, but as of today I've finished the transcript viz. fixes that I had on my list (specifically, reducing its height, and fixing some off-by-one errors with variant display). I'll start working on a prototype of the on-hover tooltips today.

**Comment by melissacline** [comment]
Thanks, Faisal!  Once you're happy with the prototype, let me know if you
could use help in moving around text.  I'm not much of a javascript
developer, but I'm good at following instructions :)

**Comment by falquaddoomi** [comment]
Thanks for the offer, although luckily I was able to scrape most of the tooltip definitions from the existing help text.

The expert-reviewed portal help markdown unfortunately needed a bit of manual annotation. Specifically, entries in `website/content/help.md` need to conform to the following format to be picked up by the tooltip scraper:
```html
<span class="tooltippable">
<em>Field Name</em>: help text to show in tooltip goes here, including HTML.
</span>
```
The field name is slugified (that is, stripped of special characters, converted to lowercase, with spaces replaced by hyphens) to associate it with the keys from the fields.

For the research-mode help text, the scraper looks for `<h4>` tags with an id attribute, then uses their surrounding siblings as the help text.

A live demo of the tooltips is available here: http://brcaexchange-dev.cloudapp.net:9005/variant/69304. (hover over a field name to display the tip)

**Comment by falquaddoomi** [comment]
Also, I think we might benefit from using this plugin, https://github.com/markdown-it/markdown-it-deflist, which adds markdown for creating definition lists, terms, and descriptions (the `<dl>`, `<dt>`, and `<dd>` tags in HTML, respectively.) It'll make extracting the tooltips from the documentation more robust as well as make our definition lists look consistent. Deflist markdown is documented here, to get an idea of what it looks like: http://pandoc.org/MANUAL.html#definition-lists.

Installing it will require us to upgrade `markdown-it`, our markdown parser, to a more contemporary version, but I don't think that'll be a big problem.

**Comment by zfisch** [comment]
@falquaddoomi is this issue resolved?

**Comment by falquaddoomi** [comment]
@zfisch Yes, I think we can say it's resolved. I'll go ahead and close it.
