### ISSUE TITLE
BRCA resources download URL going away

### ISSUE THREAD

**Issue by rcurrie** [BRCAChallenge/brca-exchange#809]
hgwdev.soe.ucsc.edu is going away as of July - or rather its being pruned down to just the UCSC browser group. So all the [download instructions](https://github.com/BRCAChallenge/brca-exchange/tree/master/pipeline) for the pipeline repo will need to change.

In its place a new GI wide public server (courtyard) is up and the new public URL's take the following form:

http://public.gi.ucsc.edu/~<username>

That said it seems to me we should really host these at a more generic location/URL controlled by the BRCA Exchange. In the short run @melissacline you can get an account on courtyard and just move these all over. Home directory limited to 30GB but you can symlink into CGL.

Thoughts/Ideas? @melissacline @izcram @zfisch

**Comment by zfisch** [comment]
Seems reasonable. We also have plenty of machines with very cheap storage where we could store these files if we want. e.g. we could just store them all on the brcaexchange.org machine or the pipeline machine.
