### ISSUE TITLE
Dockerize splicing pipeline

### ISSUE THREAD

**Issue by rcurrie** [BRCAChallenge/brca-exchange#810]
Issue to track work on dockerizing the splicing pipeline so it can be run standalone as well as to remove its dependency on the ensembl servers.

**Comment by rcurrie** [comment]
I've created a fork from master for the work: https://github.com/rcurrie/brca-exchange

**Comment by rcurrie** [comment]
Dockerized pipeline now build, tested and pushed. See [README](https://github.com/rcurrie/brca-exchange/blob/master/pipeline/splicing/README.md) for details.

@zfisch send me the error you're seeing with pytest

**Comment by zfisch** [comment]
```
zfisch@zfisch:~$ docker run -it --rm --user=`id -u`:`id -g` -v /home/zfisch/splicing/references/:/references:ro brcachallenge/splicing-pipeline test short
connect
============================================================================= test session starts ==============================================================================
platform linux2 -- Python 2.7.12, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /app, inifile:
collected 267 items

test_calcVarPriors.py .................................................................................................................................................. [ 54%]
..............................................................................................................                                                           [ 95%]
test_checkVarHGVS.py ...........                                                                                                                                         [100%]Traceback (most recent call last):
  File "calcVarPriors.py", line 3547, in <module>
    pytest.main(["-x", "."])
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 61, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 138, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/main.py", line 132, in wrap_session
    exitstatus=session.exitstatus)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/terminal.py", line 511, in pytest_sessionfinish
    outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py", line 211, in pytest_sessionfinish
    config.cache.set("cache/nodeids", self.cached_nodeids)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/cacheprovider.py", line 96, in set
    f = path.open('w')
  File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 361, in open
    return py.error.checked_call(open, self.strpath, mode)
  File "/usr/local/lib/python2.7/dist-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.EACCES: [Permission denied]: open('/app/.pytest_cache/v/cache/nodeids', 'w')
```

**Comment by rcurrie** [comment]
@zfisch Reproduced! Removing the --user works around it for the test only. Will push out a fix in a bit and notify here.

**Comment by rcurrie** [comment]
@zfisch fixed! docker pull brcachallenge/splicing-pipeline and then try again.

pytest was trying to create a cache but in the app folder which was owned by root...

**Comment by zfisch** [comment]
@rcurrie what's the expected format for running calc? I get:

```Traceback (most recent call last):
  File "calcVarPriors.py", line 3559, in <module>
    calc(args)
  File "calcVarPriors.py", line 3482, in calc
    inputData = csv.DictReader(open(args.inputFile, "r"), delimiter="\t")
IOError: [Errno 2] No such file or directory: '/home/zfisch/splicing/built_with_change_types.tsv'```

if I run:

```sudo docker run --rm -it --user=`id -u`:`id -g` -v /home/zfisch/splicing/references/:/references:ro -v /home/zfisch/splicing/built_with_change_types.tsv:/data brcachallenge/splicing-pipeline calc /home/zfisch/splicing/built_with_change_types.tsv /home/zfisch/splicing/splicing_output.tsv```

**Comment by rcurrie** [comment]
calc <path to input in the container> <path to output in the container>
You're mapping built_with_change_types.tsv to a FILE /data so the path to that in the container would just be /data, but that's probably not what you want. You probably want to:

-v /home/zfisch/splicing:/data

and then:

.... calc /data/input.tsv /data/output.tsv

Make sense?

**Comment by zfisch** [comment]
Indeed it does, thanks! I'm running the splicing code against the latest dataset (from this morning) right now -- excited to see how it does against 20,629 variants :)

**Comment by rcurrie** [comment]
I've added support to run the pipeline using multiple processes with a new --processes option. By default it spins up 8 cores but I've tested it up to 44 and seems to work just fine. Pushed a new tagged version with this in it:

```
  docker pull brcachallenge/splicing-pipeline:0.0.2
  docker run --rm -it \
    --user=`id -u`:`id -g` \
    -v `readlink -f ~/references/splicing`:/references:ro \
    brcachallenge/splicing-pipeline:latest test long -p 22
```
NOTE: Adjust references path to taste after install

Will run the integrated set of 88 variants on 22 cores and validate the output. The output is now sorted by the "HGVS_cDNA" column so that its deterministic (core's complete in a non-deterministic fashion). 

@zfisch I've split out the column headers into a separate txt file primarily as having it as a giant string in the code was awkward. In theory we can just change this file as its read in and appended to the input field names as the first row of the output file. Within the actual pipeline code though the field names are directly referenced all over the place so I don't think we should go that far and rename all of the code. Thinking we should push this out until I get a PR for the current work.

@zfisch @izcram If you're ok I'll submit a test pull request just so you can get a sense of the code motion - should be localized to just a few functions...

**Comment by zfisch** [comment]
Nice! This all makes sense. As long as the headers in the output follow the format that should be fine, and if that proves problematic, we can always adjust them in the deployment script so they're consistent in the database.

Feel free to submit a PR whenever you're ready!

FWIW, the previous output, built.tsv/built_with_change_types.tsv, was sorted in ascending order by Genomic_Coordinate_hg38 (see https://github.com/BRCAChallenge/brca-exchange/blob/master/pipeline/data_merging/variant_merging.py#L792). I'm not sure if people prefer a specific sort order, though my inclination is that any users accustomed to the data might be thrown off by a change. Either way, we don't actually store or display either of the previously mentioned fields, but rather pyhgvs_Genomic_Coordinate_hg38 and pyhgvs_cDNA (the normalized versions of those fields -- see https://github.com/BRCAChallenge/brca-exchange/blob/master/website/django/data/management/commands/addrelease.py#L104).

**Comment by rcurrie** [comment]
That sort looks better given the HGVS ambiguities, will sort the output using that and submit a PR by Monday after I look over the changes to minimize entropy.
