### ISSUE TITLE
Solve ambiguity for refDonorPrior, refAccPrior = 0.04 in ISPP sandbox

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#817]
The splicePrior can equal 0.04 for more than one reason:

- the variant improves the wild type splice site 
- the variant has null/low impact on wild type splice site

Both have been implemented in calcVarPriors.py. This ambiguity affects the splicing-level estimation nested tile (Donor Splice Site Impact tab and Acceptor Splice Impact tab), because we need to determine where to put the red box and whether it is due to improvement or null/low impact.

The existing flags may help with this differentiation:
deNovoDonorAltGreaterRefFlag
deNovoDonorAltGreaterClosestRefFlag
deNovoDonorAltGreaterClosestAltFlag
deNovoAccAltGreaterRefFlag
deNovoAccAltGreaterClosestRefFlag
deNovoAccAltGreaterClosestAltFlag

**Comment by amycoffin** [comment]
Melissa, I assigned you on this issue because the ambiguity is not yet resolved, I just indicated all that I know about it.

**Comment by amycoffin** [comment]
I am going to look into the existing flags per the spreadsheet faisal provided 
[donor, acceptor priors are 0.04](https://docs.google.com/spreadsheets/d/1hfFarfSJxqQagxFh434bZv5gy-pHBfXVdENTRtS8eJ8/edit#gid=0)

**Comment by amycoffin** [comment]
I believe that this ambiguity can simply be resolved by introducing the following conditional to the front-end implementation, and a back-end flag is unnecessary:
if altRefDonorZ > refRefDonorZ, then improved. Else, Weak/Null. 

Many variants are intronic variants with 0.04 and cannot be checked against the HCI website, but I checked 5 random variants against the HCI website and this logic seemed to be working well. The strongest argument is that it makes perfect sense conceptually, because improved inherently means that the Z score is better in alt. The concern is edge cases that would not be accounted for from this logic. The only possible edge case I can think of is when a de novo donor is so bad that it de facto improves WT splicing, which might be in the ISPP model but I doubt it...

**Comment by amycoffin** [comment]
@falquaddoomi Can you elaborate what you are saying about the de novo donor prob here?

**Comment by falquaddoomi** [comment]
@amycoffin Ah, sorry, that was more a note for myself than anything. I just added an optional 'check' condition to the data structure that stores the probabilities; the condition, if present, is evaluated against the priors data to disambiguate priors that match multiple entries.
