### ISSUE TITLE
Handle Special Case #2: Wild Type donor already has low z score; variant does not severely change z score

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#821]
Where? Splice-level Estimation nested tile/Wild Type Donor Impact tab

**Case indication per data:** 
refRefDonorZ < -2.0; | altRefDonorZ - refRefDonorZ | < 0.5

**Text implemented on HCI website to handle:**
This variant was classified as Moderate because the Z-score for the wild type is already low and the change due to variation is not considered large enough to warrant Severe. 

**Suggested text for BRCA Exchange:** 
This variant was classified as Moderate because the Z-score for the wild type is already low (less than -2) and the change due to variation is not considered large enough to warrant Severe. 

[See slide #16 on wireframes](https://docs.google.com/presentation/d/1guicEAXkN42C34W9AD0vSwbmM6RLt2W3t-pko9BihO0/edit#slide=id.g3792ea3eaf_0_26)

**Comment by falquaddoomi** [comment]
Originally implemented in commit 03dc1bf2bf7bd9824233823db10e3d6e0dd2a2df. I'll adjust the text to add the missing "(less than -2)" part shortly.

**Comment by amycoffin** [comment]
@falquaddoomi would you call this issue resolved?

**Comment by falquaddoomi** [comment]
Yes, I'd say it's resolved.
