### ISSUE TITLE
Handle Special Case #4: Wild Type acceptor already has low z score; variant does not severely change z score

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#823]
Where? Splice-level Estimation nested tile/Acceptor tab

**Indication per data:**
refAccDonorZ < -1.5; | altRefAccZ - refRefAccZ | < 0.5

**Text implemented on HCI:**
The variant was classified as Moderate because the Z score for the wildtype is already low and the change due to mutation is not considered large enough to warrant Severe.

**Suggested Text for BRCA Exchange:**
This variant was classified as Moderate because the Z-score for the wild type is already low (less than -1.5) and the change due to variation is not considered large enough to warrant Severe.

**Comment by falquaddoomi** [comment]
This looks like it's completed, but feel free to reopen if it's not.
