### ISSUE TITLE
Make intronic regions of sequences lower case

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#825]
Where? Splice-level Estimation nested tiles, all tabs

Intronic regions of sequences are lower case on the HCI website, and should be reflected similarly on BRCA Exchange.

**Comment by falquaddoomi** [comment]
Looking at the data, I don't see any examples in which there are lowercase characters in the sequence columns. Is there a column that indicates which part is the intronic vs. exonic portion of the string, or ideally can we populate the sequence columns with a case-sensitive version in calcVarPriors?

**Comment by amycoffin** [comment]
@melissacline the HCI website has intronic sequences as lower-cased. Is it okay that v1 of the priors data does not have this feature?

**Comment by melissacline** [comment]
Yes, that's totally okay.

**Comment by amycoffin** [comment]
@zfisch I think we should focus on indels, but keep this in mind when we are done. Not sure if it warrants its own issue, but the instructions from EGG were to implement per the HCI website, which does have the lower-cased features.

**Comment by zfisch** [comment]
Sounds good, we can leave it in the backlog for now and revisit when it comes back up 👍
