### ISSUE TITLE
When protein-level estimation is N/A, show N/A text instead of probability table

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#828]
When protein level estimation is N/A, the prototype currently shows the probability table with no red box. We can implement a similar format to the splice tabs when they show N/A, and there is text available in the [google doc](https://docs.google.com/document/d/1tLityUI0PSWIvBjNU5_l2OM4EFXjA9sddbeb3Cdu_SY/edit).

**Comment by melissacline** [comment]
Looks good!
