### ISSUE TITLE
Update conditionals to check for values in updated varConsequences list 

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#832]
This issue assumes that Issue #831 is resolved. 

getVarConsequences is used in 6 conditional statements to populate data based on variant consequence terms. The following methods utilize these conditionals. Most, if not all, of these conditionals should be able to be altered to basically use an "if in list" format in lieu of an "if ==" format: 

getPriorProbSpliceRescueNonsenseSNS (line 1401)
current:  `if getVarConsequences(variant) == "stop_gained" and varInExon(variant) == True: `
becomes: `if "stop_gained" in getVarConsequences(variant) and varInExon(variant ==True:
`

getPriorProbAfterGreyZoneSNS (1719),
getPriorProbSpliceDonorSNS (2216),
getPriorProbSpliceDonorSNS(2404), 
getPriorProbInExonSNS (2699), 
getPriorProbInUTRSNS( 3174)).

If the code is too buggy after changing these conditionals, revert getVarConsequences() and the associated methods above to a previous working version. Then, write an updated getVarConsequences as a new, isolated method that works and appends the column. We can problem-solve from there on how to get conditionals more accurate.

**Comment by amycoffin** [comment]
@rcurrie I am assigning you to these issues for now, because you where there but if you don't feel comfortable implementing them, feel free to just unassign yourself (and assign me). We can figure out whether Melissa or Zack will. This loop will close somewhat easily.

**Comment by rcurrie** [comment]
@amycoffin I can implement the 'in' logic but will need someone's cursory eyes on the dangling else clauses to verify that they can still be a catch all. There are a ton of consequences that can be returned and its not clear to me that all of them can be caught via the else.

**Comment by amycoffin** [comment]
@rcurrie 
1. I think it is already unclear if or how elses are actually acting as a catch all, even prior to the if-in logic being implemented. 

2. the main changes we would expect to see after if-in logic is implemented is where the first if gets thrown more often. To generalize, say that right now 2 variants have varConsequences = consequence A. Implementing the Consequence list assignment to variants might mean that we now have 4 variants that have Consequence A in consequenceList. (Assuming that 2 additional variants had it as the second item in varConsequenceList and it got missed)
Assume that a function originally runs `if x == consequence A, then True Else, False` and then is updated to run `if consequence A in list, then True Else, false ` . It would return True 2 times in the first case, while showing True 4 times in the updated case. These are the types of changes I expect to see after the logic is implemented. 

3. I am having trouble understanding why changes exhibited by (2) might introduce any _new_ problems that aren’t already occurring. Most of the code has if/elif/else structure, not if/if/structrure. I think where there is if/if/else structure, it is intentional, so I am not that worried about implementing a list instead of a string. If I should be more worried, can you explain why?
