### ISSUE TITLE
look into caching requests

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#841]
Is it worthwhile to set up caching for variant requests?

**Comment by melissacline** [comment]
There's an interesting question!  If most of the "interesting" variants are
rare, then I'd expect that each single variant gets queried rarely.  But
that's just my hunch, not based on any data.  Is there a way we could
measure this pattern, to see if caching would be useful?

We might also find a lot of repeat queries from the development team, where
we pass around URLs for specific variants...
