### ISSUE TITLE
help links in table headers no longer link to correct section of help page

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#845]
to recreate:

go to variants page
hover over a field in the header of the variants table
click the question mark that appears over the field name

expected behavior: takes user to correct section of help page
actual behavior: takes user to help page with all sections collapsed

**Comment by falquaddoomi** [comment]
It appears to be expanding the correct section for me on the latest master (65880495025a3700e88454fcd1923148393dae24). Both field and header links are expanding the correct sections on my end, but the header one is admittedly harder to notice since it doesn't highlight the panel's header.

**Comment by falquaddoomi** [comment]
Actually, this is probably a good issue to use to address the fact that section links don't scroll to that the section header in the page. I'll go ahead and do that and issue a PR referencing this issue.
