### ISSUE TITLE
Move the Community Pages paging buttons

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#86]
Feedback from Benedict:
Put the buttons to paging through resulting next to the search bar, in common with the current variants page, and try to achieve a similar look and feel.

**Comment by maryjgoldman** [comment]
I was the one who requested that we move the paging to the bottom of the page where I felt it was more natural. It also helps the screen to not feel as cluttered. What do people think of moving the paging on the current variants page to the bottom instead? @benedictpaten: what do you think?

**Comment by melissacline** [comment]
There's not enough demand for this fix.
