### ISSUE TITLE
update circleci builds

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#865]
three separate builds take place (test-pipeline, test-splicing-pipeline, and buildweb) with each push, and can report conflating results. Could you group these 3 together as a single "job" so we can easily tell if a push/deploy has issues and abort deployment if so.

**Comment by izcram** [comment]
This seems to be a known issue, and somewhat long standing...
https://discuss.circleci.com/t/2-0-notifications-are-unusable/19942
https://build.affinity.co/running-parallel-jobs-on-circleci-9fd7c6cb76f5
     
I'm going to 'sequentialise' the jobs, at the price of speed. Once circleci has fixed the issue, we can go back to parallel building

**Comment by zfisch** [comment]
Sounds good! Hopefully they get this resolved soon. The main issue for us is that we don't want a deployment to succeed or github to think a PR is safe to merge if any of the builds fail.

**Comment by zfisch** [comment]
let's sync about this after the release, I noticed our beta deploy now kicks off 13 jobs. not that the number matters, but just to make sure they're all necessary and easy to follow if there's an issue.
