### ISSUE TITLE
CI domains in data and documentation; ENIGMA or HCI??

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#866]
In the General documentation, Michael commented on CI domains stating that they are ENIGMAs. I beleive we are publishing the data per ENIGMA definitions, but theoretically it can be run using other definitions. 

I'm not sure this decision has been made clearly. We are defaulting to ENIGMA definitions per Chloe's preliminary implementation, but perhaps this is worthy of an EGG discussion?

Bottom line: Should the general document specify CI domains as ENIGMAs? Or should we leave it vague?

**Comment by amycoffin** [comment]
This may be related to issue #826

**Comment by melissacline** [comment]
@amycoffin Your mission, if you choose to accept it, is to figure out whether or not the CI domains are ENIGMA's, and to adjust the documentation accordingly.
