### ISSUE TITLE
Explore making map reactive with page size

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#87]
Feedback from Benedict: 
Make the map the same width as the table, and make it more reactive with page size.
Comments from Melissa:
Previously, the EGG weighed in on the map being smaller in size.  But perhaps the size of the map could scale with the window size?

**Comment by maryjgoldman** [comment]
I believe in the first implementation the map was the same width as the table and the EGG asked for it to be smaller. I think people were only seeing the map and the search bar on the default window size and so not realizing there was a list of people. Also I think people thought that while the map was pretty, the list of people was more important. 

Still, perhaps we could make it a bit bigger but not the width of the table? I think I remember @strbean saying there were only a few zoom levels that google has ...

Also, I think @strbean made it resize with the screen size originally but then took it out when the EGG requested it be smaller.

**Comment by falquaddoomi** [comment]
Related to this issue: on mobile devices (at least on my Nexus 5X at 412px width), the map horizontally stretches out the page, causing the menu button to appear off-screen. You can scroll right to reveal it, but it's not immediately obvious that that's the case -- it just looks like it disappeared, making it difficult to dismiss the drop-down menu.

**Comment by melissacline** [comment]
There's not enough demand to fix this.
