### ISSUE TITLE
varConsequences field not making it's way to built_with_priors.tsv

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#876]
priors output doesn't include built_with_priors.tsv as is expected

**Comment by rcurrie** [comment]
Using the docker? The [test file output](https://github.com/BRCAChallenge/brca-exchange/blob/master/pipeline/splicing/tests/priors_short.tsv) definitely have it. Let me know if this is something I should look into or if its exogenous to the splicing docker/pipeline.

**Comment by zfisch** [comment]
Interesting... the way we're running docker right now I'm not seeing it. I think we may be using the wrong docker build. E.g. when I open a shell in the container and try to run calcVarPriors it complains `ImportError: No module named pyfaidx`. Moving to slack for communication efficiency...

**Comment by zfisch** [comment]
Sure enough, the issue was that we were using an older docker image. Will update to specify which image to use
