### ISSUE TITLE
hgvs libraries cleanup

### ISSUE THREAD

**Issue by zfisch** [BRCAChallenge/brca-exchange#889]
We use both the biocommons hgvs library and the counsyl hgvs library in our codebase, though they both serve essentially the same purpose. Is there a way to remove counsyl hgvs from our codebase altogether to avoid confusion? Does messing with it cause more trouble than it's worth?

@strbean also mentioned https://github.com/zwdzwd/transvar -- would this library cover all use cases or is it a third library we would then be using?

We can address this issue as it becomes relevant during refactor or coding the indel priors.

**Comment by rcurrie** [comment]
transvar looks cool, but biocommons to my eye has significantly more support and is likeley more durable. Trying it on for size with the priors refactor before the indel addition to see if we can achieve concordance might be a good step.
