### ISSUE TITLE
Resolve Blacklisted Priors

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#890]

**Comment by amycoffin** [comment]
I am in the process of making some files/data structures for @falquaddoomi that have all the preliminary priors data and the data from sean's file.

**Comment by amycoffin** [comment]
@falquaddoomi @melissacline Sean mentioned something in an email 10 days ago about following up with Michael clinically important domains. Has this moved forward? Are we due for a conversation about the blacklisted priors?

**Comment by zfisch** [comment]
@amycoffin following up on this issue, is this resolved?

**Comment by amycoffin** [comment]
@zfisch I am not sure whether we are still using a blacklist of priors. I never really checked into things too much after Faisal did the refactoring.
