### ISSUE TITLE
Update format of Expert Reviewed Variant details per wireframes

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#919]
Please begin developing changes to Expert Reviewed side only per slide 5 of the [wireframes](https://docs.google.com/presentation/d/1qWhXI7qke1PkQzwBpZhLizA8HUVwl3fySM8gkpPaolE/edit#slide=id.g43b62ff40c_0_0). 

The implementation makes the Variant Details header smaller. It displays the GRCh38 nomenclature as large, with a small or beneath it, and then the following concatenated version of nomenclature displayed beneath the 'or':

Transcript Identifier + "(" + italicized gene name + ")" + ":" + hgvs nucleotide + "  "  + protein hgvs protein

Please also change the title of the variant nomenclature tile to "Variant Names". Also, please note that there are *no changes* to how the Help is referenced for now. 

A separate issue will be submitted to address new portal names. Other than changes related to new portal names (which will affect the blue button and the blurbs at the top of the variant results page), and new documentation, there are no other changes.

**Comment by falquaddoomi** [comment]
Did we agree that the new variant details header should just be for the expert-reviewed portal? Personally, I think it's more informative to see that text than "Variant Details" regardless of which portal you're using.

Also, for variants that don't have a protein-level change (i.e. intronic variants), I assume we can just display nothing for the protein bit?

**Comment by amycoffin** [comment]
@falquaddoomi I think for now, we are keeping it to the Expert Reviewed portal. 

If there is a p.? in the hgvs protein field, I think we should display it, but if it is null, we should not.
