### ISSUE TITLE
"More Resources..." tile on Summary View/Help links to an irrelevant paper

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#946]
Remove link on Summary View/Help/More Resources... Tile

(it links to Multifactorial Analysis paper, oops!)

**Comment by amycoffin** [comment]
<img width="883" alt="screen shot 2018-12-09 at 3 12 24 pm" src="https://user-images.githubusercontent.com/25374391/49702313-dc1f4a00-fbc4-11e8-9d5a-b3373f36ae07.png">

Here is a screenshot of where the link is, on the Summary View Help

**Comment by amycoffin** [comment]
I just noticed another weird link thing going on on Detail View Help:

<img width="875" alt="screen shot 2018-12-09 at 3 30 32 pm" src="https://user-images.githubusercontent.com/25374391/49702555-6c5e8e80-fbc7-11e8-8222-406218a5424b.png">

**Comment by falquaddoomi** [comment]
Are you seeing this on brcaexchange.org? I'm not seeing the chain-link icon in the "Outside Resources" header on my end, and I only see one link icon next to "Multifactorial Likelihood Analysis" in Detail View. I've tried it in Chrome (Windows, OS X) and Safari (OS X); let me know if you're using another browser and I'll try it there.
