### ISSUE TITLE
Name Functional Assay Data "Starita 2018 Functional Scores."

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#949]
@melissacline and I discussed that the data should be called "Starita 2018 Functional Scores" (feel free to adapt to match other titles, like Starita_2018_functional_scores, in the tsv). 

@zfisch @falquaddoomi 
Zack, it is my impression that the data we are bringing in is the functional scores alone, so this name should work. Basically each variant in this experiment will have its own functional score. This field will be blank for many of our variants. Is this the only name you needed? Is there any other executive decision making you need to integrate the true-to-form data into the sandbox?

Faisal, is the histogram currently static? Since this is a published data set, I don't think we have to worry about the histogram changing in the forseeable future. Melissa and I discussed that the UI only needs a functional score per variant. Is this correct?

Melissa, is it okay if Faisal updates the tile title to "Functional Scores (Starita 2018)"?

Docs are in the works and I will send them over to the sandbox when they are further along in the vetting process.

**Comment by zfisch** [comment]
Some of our other sources have date fields, but none of those fields are shared across data (there are often nuances to what exactly the date fields refer to). E.G.:

Date_last_evaluated_ENIGMA
Date_Last_Updated_ClinVar
Created_date_LOVD
Edited_date_LOVD
DateSignificanceLastEvaluated_ClinVar

The shared date we use across data is the release date.

**Comment by amycoffin** [comment]
Does it make any sense to just use release date? If I step back and think about a user downloading our data, I would find it confusing to navigate release date vs. date published; depending on what I originally downloaded it for, I might not even know one of those two fields exists. If it's too much to use release date, I might just vouch for our original name. Melissa should weigh in, too, though.

**Comment by zfisch** [comment]
Release date is already included :)

I'm just concerned about using a date in the source name in the case that the data is updated at some point. I imagine it would be confusing to give users data from 2019 that's listed as Starita_2018_functional_scores, and it will be a major pain to change the name throughout the app at that point.

**Comment by melissacline** [comment]
The question I hear everyone asking is "when a functional assay team updates their scores, what does that update look like?".  I don't entirely know.  I expect that they'd publish a new article, and it would contain a set of scores that's different in some way (perhaps larger in scope, perhaps using a different reporter construct, and so reporting some other aspect of functionality).  If that's true, then the older results would still be valid, but there would also be new and improved results to add in a new sub-tile.  This assumes that there's always a publication that goes with updated scores.  On Thursday, we'll be talking with Alvaro and Fergus, who are interested in developing new functional assays for BRCA1, BRCA2 and three other genes (CHEK2, PALB2, ATM).  We could ask them what they'd foresee in the way of an update process.

**Comment by falquaddoomi** [comment]
> Faisal, is the histogram currently static? Since this is a published data set, I don't think we have to worry about the histogram changing in the forseeable future. Melissa and I discussed that the UI only needs a functional score per variant. Is this correct?

It's not static per se; in the current mockup, the histogram (and functional assay score for each variant, actually) are retrieved from a local JSON file extracted from [this spreadsheet](https://docs.google.com/spreadsheets/d/1IW99Cbm-QO461kc_O3q3pamuBfXWVe7lXfo67LuCFQ0/edit#gid=949185225). The file itself is static, of course, but I've written it so it's easy to switch over to the backend when it starts supplying those values. Of course, we're not going to want to fetch the entire list of functional scores for all variants to generate the histogram, so I'm in favor of making it a static SVG at that point with the ability to easily regenerate it should we need to.

**Comment by amycoffin** [comment]
Thanks @falquaddoomi ! That's helpful. 

@zfisch, When the time comes to start integrating this data, I think that we should consider naming them ...function_scores rather than functional_scores, and I think we want to name Findlay instead of Starita. So the name might be Findlay_2018_function_scores or Findlay_function_scores. Melissa can confirm this assessment, but i think we are going to huddle about next steps soon given some feedback from yesterday's call with Alvaro, Maaike, and Fergus before moving forward too far with anything (unless you've heard otherwise from her).

**Comment by melissacline** [comment]
@Zack Fischmann <zfischma@ucsc.edu> I'd love to have a general rule for
functional assay naming, but I think it just works best on a case-by-case
basis.  Let's name for the author and scope of the data.  For this one, how
about: Findlay_BRCA1_Ring_function_scores?  As for the disclaimer, how
about this: "Attention: we have not yet received reports of this variant in
any patients".

**Comment by melissacline** [comment]
@Zack Fischmann <zfischma@ucsc.edu> one thing to have on your radar screen
is that we'll have in silico priors for a lot of the variants that  have
been seen only in the functional assays, and we'll want to report those
priors.

**Comment by zfisch** [comment]
we're currently integrating all assays into the pipeline prior to the priors 😁 so they will indeed have in silico priors where applicable
