### ISSUE TITLE
Display Descriptions of Summary/Detail View with Hover Over

### ISSUE THREAD

**Issue by amycoffin** [BRCAChallenge/brca-exchange#974]
Introduce explanatory hover-over text to the blue button, that differs depending on the view: 

"The BRCA Exchange Summary view shows clinical significance from expert review by the ENIGMA consortium.  For additional variant information, click this button and switch to Detail View."

"The BRCA Exchange Detail View shows information drawn from multiple databases which have been curated per variant. It is intended to provide professional users a set of BRCA variations and annotations which is as comprehensive as possible. For summary information with expert interpretations, click this button and switch to the Summary View."

**Comment by maryjgoldman** [comment]
Reads well! Just a few suggestions below. Take or leave them. :)

"The BRCA Exchange Summary View shows the clinical significance as reviewed by the expert ENIGMA consortium. For additional variant information, click this button to switch to the Detail View."

"The BRCA Exchange Detail View shows information drawn from multiple databases and is intended to provide professional users a set of annotations which is as comprehensive as possible. For summary information with expert interpretations, click this button to switch to the Summary View."

**Comment by falquaddoomi** [comment]
The hover-over boxes also have a header; is there any opinion about what the text in the header should be? Currently, in PR #976 that implements the above change, the text is "Change View", but I can easily change it to something else.

**Comment by falquaddoomi** [comment]
@amycoffin Would you prefer the cursor to turn into a hand icon instead? I agree that the question mark implies that the thing over which you're hovering over is static. I can also bold the text as you requested, but I think the cursor change is more subtle.

**Comment by amycoffin** [comment]
@falquaddoomi I think that is a good idea, too. I just feel like the descriptions are slightly too long for a user to actually get to the end and say, "oh i can click this to change the view." 

Also, per Mandy from EGG I think we want to tweak the wording a bit, which makes things a bit longer:

Summary view hover:
The BRCA Exchange Summary View shows the clinical significance as reviewed by the ClinGen-approved ENIGMA BRCA1/2 expert panel for variant interpretation.  For additional variant information, click this button to switch to the Detail View.
Detail view hover:
The BRCA Exchange Detail View shows information drawn from multiple databases and is intended to provide professional users with a set of annotations drawn from these external databases which is as comprehensive as possible.  For summary information, with clinical significance as reviewed by the ClinGen-approved ENIGMA BRCA1/2 expert panel, click this button to switch to the Summary View.

**Comment by amycoffin** [comment]
@zfisch I think this one is ready to close
