### ISSUE TITLE
Provide the ability to print the varaint details page

### ISSUE THREAD

**Issue by melissacline** [BRCAChallenge/brca-exchange#990]
From Marco Montagna <marco.montagna@iov.veneto.it> 

Please could you tell me if there is any way to print the results of a specific variant?
we tryed with different browsers but, once printed the different boxes inevitably overlap masking part of the information.

**Comment by zfisch** [comment]
@melissacline are there any specifics about what can and can't be omitted during print out? It may be that extra work is required to include extraneous information.
